project:
  type: book

book:
  title: מבוא להנדסת תהליכים
  author: "ענבל צרפתי-ברעד"
  chapters:
    - index.qmd
    - intro.qmd
    - chapter1.qmd
    - chapter2.qmd
    - chapter3.qmd  
    - chapter4.qmd  
    - chapter5.qmd
    - summary.qmd  
    - Bibliography.qmd

 # downloads: [pdf]        # כפתור הורדת PDF
 # output-file: "index"    # שם קובץ ה-PDF/HTML העיקרי
  sidebar:
    logo: assets/logo.png
    logo-alt: "הלוגו של הספר"
    logo-href: "/"

format:
  html:
    theme: default
    toc: true
    number-sections: true
    df-print: paged
    css:
      - assets/styles.css
      - assets/rtl-baseline.css
      - assets/site-enhance.css
    include-after-body:
      - assets/auto-env-titles.html
      - assets/chapter-numbering.html
      - assets/env-autocallouts.js
      - assets/univ-footer.html
      - assets/tracking.html
      - assets/live-exercise.html
      - assets/report-error.html
    include-in-header: _includes/head.html

#  pdf:
#    pdf-engine: xelatex         # חשוב לעברית
#    mainfont: "Arial" # או "Arial" אם מעדיפה
#    sansfont: "Arial"
#    lang: he
#    documentclass: scrreprt
#    number-sections: true
#    output-file: "process-engineering-book"
#    include-in-header:
#      - _includes/latex-he.tex

# RTL + עברית
lang: he
dir: rtl

website:
  google-analytics: "G-9L4PW59LRK"
  
# פילטרים ל-HTML
filters:
  - assets/strip-dir.lua
  - assets/env-to-callout.lua
  - assets/wordstyles-to-quarto.lua

