project:
  type: book

book:
  title: "<div class='sidebar-title'>מבוא להנדסת תהליכים</div>"
  author: "ענבל צרפתי-ברעד"
  chapters:
    - index.qmd
    - intro.qmd
    - chapter1.qmd
    - chapter2.qmd
    - chapter3.qmd  
    - chapter4.qmd  
    - chapter5.qmd  
    - Bibliography.qmd

#  downloads: [pdf]        # כפתור הורדת PDF
  output-file: "index"    # שם קובץ ה-PDF/HTML העיקרי
  sidebar:
    logo: assets/logo.png
    logo-alt: "הלוגו של הספר"
    logo-href: "/"

format:
  html:
    theme: default
    toc: true
    number-sections: true
    df-print: paged
    css:
      - assets/styles.css
      - assets/rtl-baseline.css
      - assets/site-enhance.css
    include-after-body:
      - assets/auto-env-titles.html
      - assets/chapter-numbering.html
      - assets/env-autocallouts.js
      - assets/univ-footer.html
#  pdf:
 #   pdf-engine: xelatex         # חשוב לעברית
  #  mainfont: "Arial" # או "Arial" אם מעדיפה
   # lang: he
    #documentclass: scrreprt
    #number-sections: true

# RTL + עברית
lang: he

website:
  google-analytics: "G-BCB5KL9VEP"
  
# פילטרים ל-HTML
filters:
  - assets/env-to-callout.lua
  - assets/wordstyles-to-quarto.lua

resources:
  - index.pdf

