<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="he" xml:lang="he" dir="rtl"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.7.32">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>5&nbsp; מערכות חד פאזיות – מבוא להנדסת תהליכים</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./summary.html" rel="next">
<link href="./chapter4.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-37eea08aefeeee20ff55810ff984fec1.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-ffd282cb318059e0bcb130885a47f5dc.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "אין תוצאות",
    "search-matching-documents-text": "מסמכים תואמים",
    "search-copy-link-title": "העתק קישור לחיפוש",
    "search-hide-matches-text": "הסתר התאמות נוספות",
    "search-more-match-text": "התאמה נוספת במסמך זה",
    "search-more-matches-text": "התאמות נוספות במסמך זה",
    "search-clear-button-title": "נקה",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "בטל",
    "search-submit-button-title": "שלח",
    "search-label": "חפש"
  }
}</script>
<!-- Google tag (gtag.js) -->

<script async="" src="https://www.googletagmanager.com/gtag/js?id=G-9L4PW59LRK"></script>

<script>

  window.dataLayer = window.dataLayer || [];

  function gtag(){dataLayer.push(arguments);}

  gtag('js', new Date());

  gtag('config', 'G-9L4PW59LRK');

</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="assets/styles.css">
<link rel="stylesheet" href="assets/rtl-baseline.css">
<link rel="stylesheet" href="assets/site-enhance.css">
</head>

<body class="nav-sidebar floating quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="הצג/הסתר את סרגל הניווט" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./chapter5.html"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">מערכות חד פאזיות</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="הצג/הסתר את סרגל הניווט" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="חפש" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header sidebar-header-stacked">
      <a href="./" class="sidebar-logo-link">
      <img src="./assets/logo.png" alt="הלוגו של הספר" class="sidebar-logo py-0 d-lg-inline d-none">
      </a>
    <div class="sidebar-title mb-0 py-0">
      <a href="./">מבוא להנדסת תהליכים</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="חפש"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">מבוא להנדסת תהליכים</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./intro.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span>הקדמה</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./chapter1.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title"><span>מה עושים מהנדסי ומהנדסות תהליך?</span></span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./chapter2.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title"><span>מבוא לחישובים הנדסיים</span></span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./chapter3.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title"><span>תהליכים ומשתני תהליך</span></span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./chapter4.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">מאזני חומר</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./chapter5.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">מערכות חד פאזיות</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./summary.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">סיכום</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Bibliography.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">ביבליוגרפיה</span></span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">תוכן עניינים</h2>
   
  <ul>
  <li><a href="#מה-נלמד-בפרק-הזה" id="toc-מה-נלמד-בפרק-הזה" class="nav-link active" data-scroll-target="#מה-נלמד-בפרק-הזה"><span class="header-section-number">5.1</span> מה נלמד בפרק הזה?</a></li>
  <li><a href="#מצבי-צבירה-ודיאגרמת-פאזות" id="toc-מצבי-צבירה-ודיאגרמת-פאזות" class="nav-link" data-scroll-target="#מצבי-צבירה-ודיאגרמת-פאזות"><span class="header-section-number">5.2</span> מצבי צבירה ודיאגרמת פאזות</a>
  <ul class="collapse">
  <li><a href="#מצבי-צבירה" id="toc-מצבי-צבירה" class="nav-link" data-scroll-target="#מצבי-צבירה"><span class="header-section-number">5.2.1</span> מצבי צבירה</a></li>
  </ul></li>
  <li><a href="#נוזלים-ומוצקים-קשר-בין-מסה-נפח-וצפיפות." id="toc-נוזלים-ומוצקים-קשר-בין-מסה-נפח-וצפיפות." class="nav-link" data-scroll-target="#נוזלים-ומוצקים-קשר-בין-מסה-נפח-וצפיפות."><span class="header-section-number">5.3</span> נוזלים ומוצקים: קשר בין מסה, נפח וצפיפות.</a>
  <ul class="collapse">
  <li><a href="#צפיפות-של-חומרים-טהורים" id="toc-צפיפות-של-חומרים-טהורים" class="nav-link" data-scroll-target="#צפיפות-של-חומרים-טהורים"><span class="header-section-number">5.3.1</span> צפיפות של חומרים טהורים</a></li>
  <li><a href="#צפיפות-של-תערובות-חד-פאזיות" id="toc-צפיפות-של-תערובות-חד-פאזיות" class="nav-link" data-scroll-target="#צפיפות-של-תערובות-חד-פאזיות"><span class="header-section-number">5.3.2</span> צפיפות של תערובות חד פאזיות</a></li>
  <li><a href="#סיכום---צפיפויות-של-נוזלים-וגזים" id="toc-סיכום---צפיפויות-של-נוזלים-וגזים" class="nav-link" data-scroll-target="#סיכום---צפיפויות-של-נוזלים-וגזים"><span class="header-section-number">5.3.3</span> סיכום - צפיפויות של נוזלים וגזים</a></li>
  </ul></li>
  <li><a href="#גזים-כשהנפח-תלוי-בתנאי-התהליך" id="toc-גזים-כשהנפח-תלוי-בתנאי-התהליך" class="nav-link" data-scroll-target="#גזים-כשהנפח-תלוי-בתנאי-התהליך"><span class="header-section-number">5.4</span> גזים: כשהנפח תלוי בתנאי התהליך</a>
  <ul class="collapse">
  <li><a href="#משוואת-הגז-האידיאלי" id="toc-משוואת-הגז-האידיאלי" class="nav-link" data-scroll-target="#משוואת-הגז-האידיאלי"><span class="header-section-number">5.4.1</span> משוואת הגז האידיאלי</a></li>
  <li><a href="#שימוש-במשוואת-הגז-האידיאלי-בחישובים-תהליכיים" id="toc-שימוש-במשוואת-הגז-האידיאלי-בחישובים-תהליכיים" class="nav-link" data-scroll-target="#שימוש-במשוואת-הגז-האידיאלי-בחישובים-תהליכיים"><span class="header-section-number">5.4.2</span> שימוש במשוואת הגז האידיאלי בחישובים תהליכיים</a></li>
  <li><a href="#מתי-מותר-להניח-שהגז-אידיאלי-קריטריון-האידיאליות" id="toc-מתי-מותר-להניח-שהגז-אידיאלי-קריטריון-האידיאליות" class="nav-link" data-scroll-target="#מתי-מותר-להניח-שהגז-אידיאלי-קריטריון-האידיאליות"><span class="header-section-number">5.4.3</span> מתי מותר להניח שהגז אידיאלי? (קריטריון האידיאליות)</a></li>
  <li><a href="#תערובות-של-גזים-אידיאליים" id="toc-תערובות-של-גזים-אידיאליים" class="nav-link" data-scroll-target="#תערובות-של-גזים-אידיאליים"><span class="header-section-number">5.4.4</span> תערובות של גזים אידיאליים</a></li>
  <li><a href="#סיכום---גזים-אידיאליים" id="toc-סיכום---גזים-אידיאליים" class="nav-link" data-scroll-target="#סיכום---גזים-אידיאליים"><span class="header-section-number">5.4.5</span> סיכום - גזים אידיאליים</a></li>
  </ul></li>
  <li><a href="#גזים-ריאליים" id="toc-גזים-ריאליים" class="nav-link" data-scroll-target="#גזים-ריאליים"><span class="header-section-number">5.5</span> גזים ריאליים</a>
  <ul class="collapse">
  <li><a href="#מקדם-הדחיסות-z" id="toc-מקדם-הדחיסות-z" class="nav-link" data-scroll-target="#מקדם-הדחיסות-z"><span class="header-section-number">5.5.1</span> מקדם הדחיסות Z</a></li>
  <li><a href="#משוואות-מצב-של-גזים-ריאליים" id="toc-משוואות-מצב-של-גזים-ריאליים" class="nav-link" data-scroll-target="#משוואות-מצב-של-גזים-ריאליים"><span class="header-section-number">5.5.2</span> משוואות מצב של גזים ריאליים</a></li>
  </ul></li>
  <li><a href="#סיכום" id="toc-סיכום" class="nav-link" data-scroll-target="#סיכום"><span class="header-section-number">5.6</span> סיכום</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">מערכות חד פאזיות</span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<section id="מה-נלמד-בפרק-הזה" class="level2" data-number="5.1">
<h2 data-number="5.1" class="anchored" data-anchor-id="מה-נלמד-בפרק-הזה"><span class="header-section-number">5.1</span> מה נלמד בפרק הזה?</h2>
<ul>
<li><p>להכיר את המושגים: נוזלים בלתי-דחיסים; חיבור נפחים בנוזלים; משוואת מצב; גז אידיאלי; נפח סגולי סטנדרטי; לחץ חלקי; שבר נפחי מול שבר מולרי בגזים אידיאליים; גורם דחיסות; משוואות מצב קוביות; טמפרטורה ולחץ קריטיים.</p></li>
<li><p>לחשב צפיפות או נפח של תערובת נוזלים מתוך הרכב נתון, בעזרת נתוני צפיפות או הנחת חיבור נפחים; לגזור נוסחת אומדן צפיפות.</p></li>
<li><p>ליישם את משוואת הגז האידיאלי: לחשב את המשתנה החסר, לקבוע את צפיפות הגז, ולבחון את תקפות ההנחה בעזרת גורם הדחיסות.</p></li>
<li><p>לפרש ולחשב ספיקות גזים ביחידות סטנדרטיות ובתנאי תהליך אמיתיים.</p></li>
<li><p>לקבוע הרכב תערובת גז אידיאלי מתוך לחצים חלקיים ולחץ כולל.</p></li>
<li><p>לבצע חישובי PVT בעזרת משוואות מצב שונות (ויריאל, ואן-דר-ואלס, SRK, compressibility factor).</p></li>
<li><p>לנתח ולפתור מערכות תהליך עם ספיקות נפחיות: לבצע ניתוח דרגות חופש, לנסח משוואות, לחשב ולרשום הנחות, ולבחון את סבירותן.</p></li>
</ul>
</section>
<section id="מצבי-צבירה-ודיאגרמת-פאזות" class="level2" data-number="5.2">
<h2 data-number="5.2" class="anchored" data-anchor-id="מצבי-צבירה-ודיאגרמת-פאזות"><span class="header-section-number">5.2</span> מצבי צבירה ודיאגרמת פאזות</h2>
<p>כאשר מהנדס או מהנדסת ניגשים לתכנן או לנתח מערכת תהליכית, נדרש לעיתים לקבוע תכונות פיזיקליות של חומרי התהליך ולהשתמש בהן כחלק מתיאור המערכת. תכונות אלו מאפשרות לקשור בין משתנים שונים, ולגזור קשרים הכרחיים לצורך חישובי מאזן החומר וניתוח הזרמים במערכת.</p>
<p>תכונות פיזיקליות, כגון צפיפות, אינן תמיד ידועות מראש בתנאי העבודה הרלוונטיים. לשם קביעתן נעזרים במקורות מידע שונים, בהם טבלאות נתונים ניסיוניים, מאגרי מידע, וקורלציות אמפיריות המתארות את תלות התכונה בטמפרטורה ולעיתים גם בלחץ. הבחירה בדרך המתאימה לקביעת התכונה, ורמת הדיוק הנדרשת, הן חלק משיקול הדעת ההנדסי.</p>
<section id="מצבי-צבירה" class="level3" data-number="5.2.1">
<h3 data-number="5.2.1" class="anchored" data-anchor-id="מצבי-צבירה"><span class="header-section-number">5.2.1</span> מצבי צבירה</h3>
<p>חומרי תהליך יכולים להופיע כמוצקים, נוזלים או גזים, כאשר מצב הצבירה תלוי בתנאי התהליך, ובראשם הטמפרטורה והלחץ. בניתוח תהליכים, מצב הצבירה קובע כיצד נבחר לתאר את החומר ואילו תכונות פיזיקליות יהיו רלוונטיות. נוזלים ומוצקים מתאפיינים בנפח כמעט קבוע ובתלות חלשה בלחץ, ולכן ניתן לרוב לתארם כחומרים בלתי־דחיסים בקירוב. לעומתם, גזים מתאפיינים בנפח התלוי באופן חזק בתנאי התהליך, ודורשים טיפול שונה, כפי שנראה בהמשך הפרק.</p>
<p>מעברים בין מצבי צבירה, כגון אידוי, עיבוי או התכה, מתרחשים כאשר תנאי התהליך משתנים וחוצים גבולות בין אזורי יציבות שונים. גבולות אלו מתוארים באמצעות דיאגרמות פאזות, המציגות את תחומי הקיום של כל מצב צבירה ואת תנאי המעבר ביניהם. דיאגרמות אלו משמשות כלי תיאורי חשוב להבנת מצב החומר בתהליך, אך בקורס זה נשתמש בהן בעיקר לצורך זיהוי תחום העבודה ולא לצורך ניתוח תרמודינמי מפורט.</p>
<div class="callout callout-style-simple callout-note no-icon">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-body-container">
<p>אינטראקציה: דיאגרמת הפאזות</p>
<p>שחקו עם הדיאגרמה כדי לראות את הקשר בין הלחץ והטמפרטורה למצב הצבירה.</p>
<iframe src="simulations/phase.html" width="100%" height="600px" style="border:none;">
</iframe>
<p><strong>שאלות מנחות לחקירה:</strong></p>
<ol type="1">
<li><p><strong>הגבול של לחץ נמוך:</strong> הציבו את המחוון על טמפרטורה כלשהי. מהו ערכו של <span class="math inline">\(z\)</span> כאשר הלחץ מתקרב ל-0 אטמוספירות? האם ערך זה משתנה כשמחליפים בין הגזים השונים?</p></li>
<li><p><strong>השפעת הטמפרטורה:</strong> בחרו את הגז <strong>מתאן (<span class="math inline">\(CH_4\)</span>)</strong>. התחילו בטמפרטורה נמוכה (סביב <span class="math inline">\(200K\)</span>) והעלו אותה בהדרגה ל-<span class="math inline">\(500K\)</span>. כיצד משפיעה העלאת הטמפרטורה על הסטייה מהתנהגות אידיאלית (<span class="math inline">\(z=1\)</span>)?</p></li>
<li><p><strong>השוואה בין חומרים:</strong> קבעו את הטמפרטורה על <span class="math inline">\(300K\)</span>. החליפו בין <strong>חנקן (<span class="math inline">\(N_2\)</span>)</strong> לבין <strong>פחמן דו-חמצני (<span class="math inline">\(CO_2\)</span>)</strong>. איזה מהגזים מציג סטייה גדולה יותר מאידיאליות בטמפרטורה זו, ומדוע? (רמז: בדקו את הערך של <span class="math inline">\(T_c\)</span> המוצג עבור כל גז).</p></li>
<li><p><strong>מעבר פאזה:</strong> בחרו ב<strong>מים (<span class="math inline">\(H_2O\)</span>)</strong> והורידו את הטמפרטורה אל מתחת ל-<span class="math inline">\(647K\)</span>. מה קורה לצורת הגרף בלחצים נמוכים? (הלולאה שנוצרת מייצגת את אזור הדו-פאזי שבו הגז מתעבה לנוזל, כפי שמתואר במשוואת ואן-דר-ואלס).</p></li>
</ol>
</div>
</div>
</div>
<p>בניתוח תהליכים נהוג להבחין בין מערכות חד־פאזיות למערכות רב־פאזיות.</p>
<div class="callout callout-note definition" title="הגדרה" data-collapse="false">
<p>פאזה היא אזור במערכת שבו החומר אחיד בתכונותיו הפיזיקליות והכימיות, כגון הרכב, צפיפות וטמפרטורה.</p>
</div>
<div class="callout callout-note definition" title="הגדרה" data-collapse="false">
<p>מערכת חד־פאזית היא מערכת שבה קיים אזור כזה בלבד, כלומר כל החומר נמצא באותו מצב צבירה ובעל תכונות אחידות.</p>
</div>
<p>דוגמאות למערכות חד־פאזיות כוללות נוזל טהור במיכל, תמיסה נוזלית אחידה, או זרם גז אחיד בצינור. במערכות אלו ניתן לייחס לכל המערכת ערך יחיד של צפיפות, טמפרטורה והרכב, דבר המאפשר תיאור פשוט יחסית של הזרמים וחישובי מאזן החומר.</p>
<p>לעומת זאת, במערכת רב־פאזית מתקיימים בו־זמנית אזורים נפרדים בעלי תכונות שונות, כגון נוזל וגז, או מוצק ונוזל. במערכות כאלה אין אפשרות לתאר את המערכת כולה באמצעות ערך יחיד של צפיפות או הרכב, ונדרש טיפול נפרד בכל פאזה. ניתוח מערכות רב־פאזיות מורכב יותר, וידרוש כלים נוספים שלא נעסוק בהם בשלב זה.</p>
<p>במערכות חד־פאזיות, שבהן ניתן לייחס לחומר תכונות אחידות, ניתן להשתמש בצפיפות כקשר ישיר בין תיאורים נפחיים לבין כמויות חומר. קשר זה מהווה בסיס לעבודה עם זרמים של נוזלים ומוצקים בתיאור תהליכים.</p>
<div class="callout callout-important exercise" title="תרגיל" data-collapse="false">
<p>עבור כל אחת מהמערכות הבאות, קבעו האם מדובר במערכת <strong>חד-פאזית</strong> או <strong>רב-פאזית</strong><br>
א. כוס מים עם קרח.<br>
ב. תרכיז פטל שנמהל במים בצורה מושלמת.<br>
ג. בקבוק סודה שנפתח זה עתה (ויוצאות ממנו בועות).</p>
</div>
<div class="callout callout-style-default callout-note callout-titled" title="פתרון">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-1-contents" aria-controls="callout-1" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
פתרון
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-1" class="callout-1-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>א. <strong>כוס מים עם קרח: רב-פאזית.</strong> למרות שזהו אותו חומר כימי (<span class="math inline">\(\mathbf{H}_{\mathbf{2}}\mathbf{O}\)</span>), יש כאן שני מצבי צבירה שונים (מוצק ונוזל) עם גבול ברור ביניהם, ותכונות שונות (כמו צפיפות) לכל מצב צבירה.</p>
<p>ב. <strong>תרכיז שנמהל: חד-פאזית.</strong> הנוזל אחיד בכל נפחו. אין גבולות פנימיים המפרידים בין המים לתרכיז (זו תמיסה), ובכל נקודה במערכת התכונות הפיסיקליות יהיו זהות</p>
<p>ג. <strong>בקבוק סודה פתוח: רב-פאזית.</strong> יש כאן פאזה נוזלית (המשקה) ופאזה גזית (בועות הפחמן הדו-חמצני) הנמצאות במגע.</p>
</div>
</div>
</div>
</section>
</section>
<section id="נוזלים-ומוצקים-קשר-בין-מסה-נפח-וצפיפות." class="level2" data-number="5.3">
<h2 data-number="5.3" class="anchored" data-anchor-id="נוזלים-ומוצקים-קשר-בין-מסה-נפח-וצפיפות."><span class="header-section-number">5.3</span> נוזלים ומוצקים: קשר בין מסה, נפח וצפיפות.</h2>
<p>עד כה, ברוב הדוגמאות והתרגילים בקורס, תיארנו כמויות חומר במונחים של מסה או מספר מולים. זו בחירה טבעית: מאזן החומר מבוסס על שימור מסה, וסטוכיומטריה מנוסחת במונחים מולריים. אולם כאשר עוברים מתיאור כימי מופשט לתיאור של תהליך זורם בפועל, מתברר שאלו אינם המשתנים הנוחים ביותר לעבודה. במערכות תהליכיות אמיתיות חומר אינו “נספר” במולים ואינו “נשקל” בכל רגע, אלא זורם בצינורות, נשאב במשאבות ונמדד לרוב ביחידות של נפח ליחידת זמן. לכן, כדי לנתח ולפתור מערכות זורמות, עלינו לדעת לקשר בין תיאורים מבוססי מסה או מולים לבין תיאורים מבוססי נפח.</p>
<p>במערכות תהליכיות רבות, ובפרט כאשר עוסקים בנוזלים, המשתנה הנפחי הוא נקודת המוצא לחישוב. מיכלים, צינורות, משאבות ומערכות אגירה מתוכננים לפי נפח, והמידע התפעולי הניתן על תהליך מתייחס לרוב לנפחים או לספיקות נפחיות. במקרים רבים נוכל לחשב מסה מתוך נפח נתון (או להפך) באמצעות הקשר הפשוט</p>
<p><span class="math display">\[m = \rho V\]</span> כאשר הצפיפות נחשבת קבועה בתנאי התהליך הנתונים. עבור נוזלים ומוצקים, זוהי לעיתים קרובות הנחה סבירה, שכן נפחם משתנה מעט בלבד עם לחץ וטמפרטורה בטווחי עבודה תעשייתיים.</p>
<p>עם זאת, בקביעת ערכי צפיפות כחלק מתיאור תהליך, ערכים אלו אינם תמיד זמינים ישירות, ולעיתים נדרש לאתרם ממקורות חיצוניים. לצורך כך עומדים לרשותנו סוגים שונים של נתונים פיזיקליים: טבלאות נתונים ניסיוניים, ערכים מדודים בתנאים סטנדרטיים, וקורלציות אמפיריות המתארות את תלות הצפיפות בטמפרטורה ולעיתים גם בלחץ.</p>
<section id="צפיפות-של-חומרים-טהורים" class="level3" data-number="5.3.1">
<h3 data-number="5.3.1" class="anchored" data-anchor-id="צפיפות-של-חומרים-טהורים"><span class="header-section-number">5.3.1</span> צפיפות של חומרים טהורים</h3>
<p>צפיפות היא תכונה פיזיקלית אינטנסיבית, המגדירה את היחס בין מסה לנפח של חומר. עבור חומרים טהורים, הצפיפות נקבעת על ידי זהות החומר ותנאי התהליך, ובראשם הטמפרטורה והלחץ. במוצקים ובנוזלים, השפעת הטמפרטורה על הצפיפות היא לרוב משמעותית, בעוד שתלות הצפיפות בלחץ חלשה יחסית וניתנת להזנחה ברוב טווחי העבודה התעשייתיים.</p>
<p>במערכות תהליכיות, הצפיפות משמשת לקישור בין תיאורים נפחיים של זרמים - כפי שהם נמדדים ומבוקרים בפועל - לבין כמויות חומר במונחים של מסה או מולים, הנדרשות לצורך חישובי מאזן חומר. לכן, קביעת ערך צפיפות מתאים אינה שלב טכני שולי, אלא חלק מרכזי בתיאור המערכת.</p>
<section id="תנאים-סטנדרטיים-standard-conditions" class="level4" data-number="5.3.1.1">
<h4 data-number="5.3.1.1" class="anchored" data-anchor-id="תנאים-סטנדרטיים-standard-conditions"><span class="header-section-number">5.3.1.1</span> תנאים סטנדרטיים (Standard Conditions)</h4>
<p>מכיוון שנפח (ולכן גם צפיפות) משתנה כתלות בטמפרטורה ובלחץ, קיים צורך בבסיס משותף להשוואה ולדיווח נתונים. בסיס זה מכונה "תנאים סטנדרטיים", והוא משתנה בין ענפי תעשייה ובין ארגונים מדעיים (כגון IUPAC מול תעשיית הגז והנפט).</p>
<p>בהנדסה כימית ובתהליכים, מקובל להיתקל בשתי הגדרות נפוצות:</p>
<div class="callout callout-note definition" title="הגדרה" data-collapse="false">
<ol type="1">
<li><p><strong>STP (Standard Temperature and Pressure) -</strong> מוגדר לרוב כטמפרטורה של <span class="math inline">\(0^{\circ}C\)</span> (<span class="math inline">\(273.15\ K\)</span>) ולחץ של <span class="math inline">\(1\text{ atm}\)</span> (או <span class="math inline">\(1\text{ bar}\)</span> בתקנים חדשים יותר). הגדרה זו נפוצה מאוד בחישובי גזים.</p></li>
<li><p><strong>SATP (Standard Ambient Temperature and Pressure) -</strong> המכונים לעיתים "תנאי חדר", מוגדרים כטמפרטורה של <span class="math inline">\(25^{\circ}C\)</span> (<span class="math inline">\(298.15\ K\)</span>) ולחץ של <span class="math inline">\(1\text{ bar}\)</span>. נתונים רבים לנוזלים ולמוצקים מדווחים סביב טמפרטורה זו.</p></li>
</ol>
</div>
<p>כאשר אתם שולפים נתון צפיפות מטבלה המציינת "תנאים סטנדרטיים" או מסומנת בקיצור S.C, בדקו תמיד באותיות הקטנות או במבוא לטבלה מהי הטמפרטורה אליה מתייחס המקור, שכן ההבדל בין <span class="math inline">\(0^{\circ}C\)</span> ל-<span class="math inline">\(25^{\circ}C\)</span> עשוי להיות משמעותי.</p>
</section>
<section id="שימוש-בנתונים-טבלאיים" class="level4" data-number="5.3.1.2">
<h4 data-number="5.3.1.2" class="anchored" data-anchor-id="שימוש-בנתונים-טבלאיים"><span class="header-section-number">5.3.1.2</span> שימוש בנתונים טבלאיים</h4>
<p>הדרך הנפוצה ביותר לקביעת צפיפות של חומר טהור היא שימוש בנתונים ניסיוניים שפורסמו בספרות המקצועית ובמאגרי נתונים. צפיפויות של חומרים רבים נמדדו בתנאים מבוקרים, וערכיהן זמינים בטבלאות נתונים ובספרי ייחוס. נתונים אלו מהווים נקודת מוצא אמינה, וניתן להשתמש בהם ישירות כאשר תנאי המדידה קרובים לתנאי התהליך הנבחן.</p>
<p>נתונים ניסיוניים לתכונות פיזיקליות של חומרים זמינים במגוון מקורות ייעודיים. מקורות נפוצים כוללים ספרי ייחוס להנדסת תהליכים, כגון ספרי יד (handbooks) ומאגרי נתונים מקוונים, המרכזים ערכים שנמדדו בתנאים מבוקרים. מאגרים אלה מספקים מידע על צפיפות, לחצי אדים, מסיסות ותכונות נוספות, ולעיתים כוללים גם תלות בטמפרטורה ובלחץ. השימוש במקורות מסוג זה מאפשר להסתמך על נתונים מבוססים, ולהימנע מהנחות שרירותיות או ממידע שאינו מתועד כראוי.</p>
<p>נתונים לתכונות פיזיקליות של חומרים, כגון צפיפות, זמינים במאגרי נתונים ייעודיים ובספרי יד להנדסת תהליכים. מקורות נפוצים כוללים את <em>CRC Handbook of Chemistry and Physics</em>, את <em>Perry’s Chemical Engineers’ Handbook</em>, ואת מאגר הנתונים המקוון <em>NIST Chemistry WebBook</em>. מקורות אלה מרכזים נתונים ניסיוניים שנמדדו בתנאים מבוקרים, ולעיתים כוללים גם תלות בטמפרטורה ובלחץ. בעת שימוש בנתונים, חשוב לשים לב לתנאי המדידה ולוודא התאמה לתנאי התהליך הנבחן. לעיתים ניתן להסתפק בקירוב, ולעיתים נדרש תיקון או שימוש בנתונים נוספים, בהתאם לרמת הדיוק הנדרשת ולמטרת החישוב.</p>
<div class="callout callout-important exercise" title="תרגיל" data-collapse="false">
<p>לגליצרול טהור זמינים הנתונים הבאים:</p>
<p>מקור א: <span class="math inline">\(\mathbf{\rho} = \mathbf{1}.\mathbf{26134}\text{ }\mathbf{g}/\mathbf{mL}\)</span>בטמפרטורה <span class="math inline">\(\mathbf{20}^{\circ}\mathbf{C}\)</span></p>
<p>מקור ב: <span class="math inline">\(\mathbf{\rho} = \mathbf{1}.\mathbf{23970}\text{ }\mathbf{g}/\mathbf{mL}\)</span>בטמפרטורה <span class="math inline">\(\mathbf{60}^{\circ}\mathbf{C}\)</span></p>
<p>הזרם בתהליך נמצא בטמפרטורה <span class="math inline">\(\mathbf{25}^{\circ}\mathbf{C}\)</span>.<br>
באיזה נתון כדאי להשתמש כדי להמיר ספיקה נפחית לספיקה מסתית? נמקו בקצרה.</p>
</div>
<div class="callout callout-style-default callout-note callout-titled" title="פתרון">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-2-contents" aria-controls="callout-2" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
פתרון
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-2" class="callout-2-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>כדאי להשתמש במקור א’ (הנתון ב־<span class="math inline">\(\mathbf{20}^{\circ}\mathbf{C}\)</span>) משום שהוא קרוב יותר לתנאי התהליך <span class="math inline">\(\mathbf{25}^{\circ}\mathbf{C}\)</span>. צפיפות של נוזלים משתנה עם טמפרטורה, ולכן נתון שנמדד קרוב יותר לטמפרטורת העבודה צפוי להקטין את השגיאה. במקרה הזה, שימוש בנתון ב־<span class="math inline">\(\mathbf{60}^{\circ}\mathbf{C}\)</span> עלול להוביל להערכת חסר של הצפיפות (ומכאן גם של המסה), כי בטמפרטורות גבוהות יותר הצפיפות נמוכה יותר.</p>
<p>כאשר נדרש דיוק גבוה יותר, נעדיף לבצע תיקון טמפרטורה באמצעות קורלציה או אינטרפולציה בין נתונים.</p>
</div>
</div>
</div>
</section>
<section id="שימוש-בקורלציות-אמפיריות" class="level4" data-number="5.3.1.3">
<h4 data-number="5.3.1.3" class="anchored" data-anchor-id="שימוש-בקורלציות-אמפיריות"><span class="header-section-number">5.3.1.3</span> שימוש בקורלציות אמפיריות</h4>
<p>כאשר נדרש ערך צפיפות בטמפרטורה שונה מזו של הנתונים הזמינים, ניתן להיעזר בקורלציות אמפיריות המתארות את תלות הצפיפות בטמפרטורה. קורלציות אלו הן ביטויים מתמטיים פשוטים יחסית, אשר הותאמו לנתונים ניסיוניים בטווח מוגדר של תנאים.</p>
<p>השימוש בקורלציות מאפשר לבצע אינטרפולציה בין נקודות מדידה ידועות, ולעיתים גם אקסטרפולציה זהירה. עם זאת, יש לזכור כי קורלציות אינן חוקי טבע, ותקפותן מוגבלת לטווח התנאים שלפיהם פותחו. לכן, בעת שימוש בהן יש לבדוק את תחום התקפותן ולהעריך את השפעת אי־הוודאות על תוצאות החישוב.</p>
<div class="callout callout-important exercise" title="תרגיל" data-collapse="false">
<p>בטקסט נכתב כי "קורלציות אינן חוקי טבע". מהי המשמעות המעשית של משפט זה עבור מהנדס שצריך לחשב צפיפות בטמפרטורה של <span class="math inline">\(\mathbf{8}\mathbf{0}^{\mathbf{\circ}}\mathbf{C}\)</span> כאשר הקורלציה שבידיו פותחה על סמך נתונים בטווח של <span class="math inline">\(\mathbf{1}\mathbf{0}^{\mathbf{\circ}}\mathbf{C - 6}\mathbf{0}^{\mathbf{\circ}}\mathbf{C}\)</span>? נמקו</p>
</div>
<div class="callout callout-style-default callout-note callout-titled" title="פתרון">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-3-contents" aria-controls="callout-3" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
פתרון
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-3" class="callout-3-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>אם יש נתון יותר מדוייק נעדיף לעבוד איתו, אבל אם אין לנו נתון יותר מדוייק, ואנחנו מחפשים רק ערך ראשוני של סדר גודל, עדיף להשתמש באקסטרפוציה לקורלציה, תוך בדיקה רציפה בדיעבד האם הערך הגיוני.</p>
</div>
</div>
</div>
</section>
<section id="מדידה-ניסיונית" class="level4" data-number="5.3.1.4">
<h4 data-number="5.3.1.4" class="anchored" data-anchor-id="מדידה-ניסיונית"><span class="header-section-number">5.3.1.4</span> מדידה ניסיונית</h4>
<p>במקרים שבהם לא ניתן למצוא נתונים מתאימים בספרות, או כאשר נדרש דיוק גבוה במיוחד, הצפיפות נקבעת באמצעות מדידה ניסיונית. בכל מערכת יש גורמים רבים שמשפיעים ולא תמיד ניתן למדל את כולם, הדרך הכי מדוייקת לדעת את התכונות של חומר מסויים בתנאים מסויימים היא למדוד אותן. מדידות כאלה מבוצעות באמצעים ניסיוניים ייעודיים, ונפוצות במיוחד בשלבי פיתוח תהליך, בעבודה עם חומרים חדשים, או כאשר תנאי התהליך חורגים משמעותית מן התנאים הסטנדרטיים. מדידה ניסיונית מאפשרת לקבוע את הצפיפות בתנאים המדויקים של המערכת, אך היא כרוכה בזמן, בעלות ובמאמץ ניסויי. משום כך, היא משמשת בדרך כלל כאשר הדיוק חשוב ושימוש בנתונים קיימים או בקורלציות אינו מספק מענה מתאים.</p>
</section>
<section id="בחירת-מקור-הנתונים" class="level4" data-number="5.3.1.5">
<h4 data-number="5.3.1.5" class="anchored" data-anchor-id="בחירת-מקור-הנתונים"><span class="header-section-number">5.3.1.5</span> בחירת מקור הנתונים</h4>
<p>הבחירה בין שימוש בנתונים טבלאיים, קורלציות אמפיריות או מדידה ניסיונית תלויה במטרת החישוב, ברמת הדיוק הנדרשת ובשלב שבו נמצא התהליך ההנדסי. במקרים רבים, ניתוח ראשוני או חישוב סדר גודל יתבססו על נתונים זמינים וקירובים פשוטים, בעוד שבשלבים מתקדמים יותר יידרש שימוש בנתונים מדויקים יותר. היכולת לבחור מקור נתונים מתאים ולהעריך את סבירותו היא חלק בלתי נפרד מן החשיבה ההנדסית.</p>
<div class="callout callout-important exercise" title="תרגיל" data-collapse="false">
<p>בחרו את מקור הנתונים המתאים ביותר בכל מצב (מתוך האפשרויות: טבלה, קורלציה, מדידה ניסיונית). נמקו</p>
<ol type="1">
<li><p>תכנון סופי של מערכת תעשייתית, שבה טעות של <span class="math inline">\(2\%\)</span> בצפיפות תגרום לחריגה משמעותית בעמידה במפרט מוצר.</p></li>
<li><p>חישוב ראשוני (סדר גודל) לצורך סקיצה של קטרי צנרת במערכת חדשה.</p></li>
<li><p>נדרש ערך צפיפות בטמפרטורה <span class="math inline">\(55^{\circ}C\)</span>, ויש טבלה רק ב-<span class="math inline">\(20^{\circ}C\)</span>, אך קיימת קורלציה התקפה עד <span class="math inline">\(80^{\circ}C\)</span>.</p></li>
</ol>
</div>
<div class="callout callout-style-default callout-note callout-titled" title="פתרון">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-4-contents" aria-controls="callout-4" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
פתרון
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-4" class="callout-4-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><strong>1. מדידה ניסיונית</strong> (או נתונים ניסיוניים מאוד ספציפיים לתנאי התהליך, אם קיימים) - כי דרוש דיוק גבוה והשפעת השגיאה קריטית.</p>
<p><strong>2. טבלה</strong> (או ערך סטנדרטי אמין) - כי המטרה היא סדר גודל ולא נדרש דיוק גבוה.</p>
<p><strong>3. קורלציה</strong> - כי היא מאפשרת התאמה לטמפרטורה הרצויה בתוך תחום התקפות, בעוד שטבלה ב-<span class="math inline">\(20^{\circ}C\)</span> אינה מתאימה ישירות.</p>
</div>
</div>
</div>
</section>
</section>
<section id="צפיפות-של-תערובות-חד-פאזיות" class="level3" data-number="5.3.2">
<h3 data-number="5.3.2" class="anchored" data-anchor-id="צפיפות-של-תערובות-חד-פאזיות"><span class="header-section-number">5.3.2</span> צפיפות של תערובות חד פאזיות</h3>
<p>עד כה עסקנו בקביעת צפיפות של חומרים טהורים במערכות חד־פאזיות, שבהן ניתן לייחס לחומר ערך צפיפות יחיד בתנאי תהליך נתונים. כאשר החומר במערכת הוא תערובת של נוזלים, מתווסף משתנה חדש - ההרכב - ולכן הצפיפות אינה תכונה “נתונה מראש” אלא תוצאה של שילוב הרכיבים. במצב כזה נדרש לקשר בין הרכב התערובת לבין הנפח הכולל שלה, כדי שנוכל להמשיך ולהמיר בין תיאורים נפחיים לבין מסה או מולים לצורך חישובי מאזן חומר.</p>
<p>כאשר עוסקים בחומר טהור, הקשר בין מסה לנפח נקבע באמצעות ערך צפיפות יחיד. אולם כאשר החומר במערכת הוא תערובת של נוזלים, מתעוררת שאלה עקרונית: כיצד נקבע נפח התערובת מתוך נפחי הרכיבים המרכיבים אותה?</p>
<p>באופן אינטואיטיבי, ניתן לחשוב שנפח תערובת של שני נוזלים שווה לסכום נפחיהם לפני הערבוב. כלומר, אם מערבבים נפח נתון של נוזל אחד עם נפח נתון של נוזל אחר, ניתן לצפות שהנפח הכולל יהיה פשוט סכום שני הנפחים. אינטואיציה זו נפוצה, והיא משמשת לעיתים כהנחת עבודה סמויה. עם זאת, מבחינה פיזיקלית אין הכרח שנפחי הרכיבים יתחברו בצורה פשוטה. ערבוב נוזלים עשוי לגרום לשינוי בסידור המולקולרי, ולפיכך גם לשינוי בנפח הכולל. לכן, אף על פי שבפועל נהוג לעיתים להשתמש בחיבור נפחים באופן ישיר כחלק מחישוב תהליכי, אין לראות בכך צעד אוטומטי. חיבור נפחים הוא הנחת עבודה שיש להכיר בה במפורש, ולהבין באילו מצבים היא סבירה ובאילו מקרים היא עלולה להוביל לשגיאה.</p>
<section id="אדטיביות-של-נפחים" class="level4" data-number="5.3.2.1">
<h4 data-number="5.3.2.1" class="anchored" data-anchor-id="אדטיביות-של-נפחים"><span class="header-section-number">5.3.2.1</span> אדטיביות של נפחים</h4>
<div class="callout callout-note definition" title="הגדרה" data-collapse="false">
<p><strong>הנחת חיבור נפחים (אדטיביות של נפחים)</strong> נפח התערובת שווה לסכום נפחי הרכיבים המרכיבים אותה לפני הערבוב. כלומר, אם תערובת מורכבת ממספר רכיבים, כל אחד בנפח נתון, אזי הנפח הכולל של התערובת מתקבל מחיבור נפחי הרכיבים.</p>
</div>
<p>הנחה זו מאפשרת לקשר בין הרכב התערובת לבין נפחה בצורה ישירה, ולכן גם לחשב צפיפות תערובת מתוך צפיפויות הרכיבים. במונחים חישוביים, היא מפשטת את הבעיה באופן משמעותי, ומאפשרת להמשיך לעבוד עם תיאורים נפחיים כחלק מניתוח תהליכים זורמים. עם זאת, חשוב להדגיש כי מדובר <strong>בהנחה ולא בחוק פיזיקלי</strong> .חיבור נפחים אינו מובטח מבחינה עקרונית, והוא משקף קירוב שבו מניחים כי ערבוב הרכיבים אינו גורם לשינוי נפח כולל. הנחה זו סבירה בעיקר כאשר מדובר בנוזלים בעלי מבנה מולקולרי דומה, או כאשר השפעת האינטראקציות בין הרכיבים על הנפח הכולל קטנה ביחס לדיוק הנדרש בחישוב.</p>
</section>
<section id="חישוב-צפיפות-של-תערובת" class="level4" data-number="5.3.2.2">
<h4 data-number="5.3.2.2" class="anchored" data-anchor-id="חישוב-צפיפות-של-תערובת"><span class="header-section-number">5.3.2.2</span> חישוב צפיפות של תערובת</h4>
<p>בהנחת חיבור נפחים, ניתן לחשב את צפיפותה של תערובת נוזלים בשתי דרכים שונות, בהתאם לאופן שבו הרכב התערובת נתון. אף ששתי הדרכים נשענות על אותה הנחת עבודה, הן מבוססות על תיאורי הרכב שונים - שברי מסה לעומת שברי נפח - ולכן אינן בהכרח מניבות את אותה תוצאה. ההבדל בין התוצאות נובע מכך שהמעבר בין תיאורי ההרכב אינו טריוויאלי ותלוי בצפיפויות הרכיבים.</p>
<p><u>חישוב צפיפות תערובת מתוך שברי נפח</u></p>
<p>כעת נבחן תערובת של שני נוזלים, A ו־B, כאשר הרכב התערובת נתון באמצעות שברי נפח <span class="math inline">\(\phi_{A}\)</span>, <span class="math inline">\(\phi_{B}\)</span>. בהנחת חיבור נפחים, הנפח הכולל הוא סכום נפחי הרכיבים, והמסה של כל רכיב מתקבלת כמכפלת נפחו בצפיפותו. צפיפות התערובת מתקבלת לכן כ־</p>
<p><span class="math display">\[\rho_{\text{mix}} = \phi_{A}\rho_{A} + \phi_{B}\rho_{B}\]</span></p>
<div class="callout callout-note definition" title="הגדרה" data-collapse="false">
<p>כאשר יש לנו את השברים הנפחיים, צפיפות תערובת עבור תערובת עם n רכיבים תהיה</p>
<p><span class="math display">\[\rho_{\text{mix}} = \sum_{i = 1}^{n}\phi_{i}\rho_{i}\]</span> כאשר <span class="math inline">\(i\)</span> הוא הרכיב, <span class="math inline">\(\rho_{i}\)</span> זו צפיפות הרכיב ו-<span class="math inline">\(\phi_{i}\)</span> הוא השבר הנפחי של הרכיב בתמיסה.</p>
</div>
<p><u>חישוב צפיפות תערובת מתוך שברי מסה</u></p>
<p>נבחן תחילה תערובת חד־פאזית של שני נוזלים, A ו-B. נסמן את המסות של הרכיבים ב־<span class="math inline">\(m_{A}\)</span>, <span class="math inline">\(m_{B}\)</span>, ואת צפיפויותיהם ב־<span class="math inline">\(\rho_{A}\)</span>, <span class="math inline">\(\rho_{B}\)</span>. צפיפות התערובת מוגדרת כיחס בין המסה הכוללת לבין הנפח הכולל:</p>
<p><span class="math display">\[\rho_{\text{mix}} = \frac{m_{A} + m_{B}}{V_{A} + V_{B}}\]</span> בהנחת חיבור נפחים, נפח כל רכיב בנפרד מתקבל מחלוקת המסה שלו בצפיפות המתאימה:</p>
<p><span class="math display">\[V_{A} = \frac{m_{A}}{\rho_{A}},V_{B} = \frac{m_{B}}{\rho_{B}}\]</span></p>
<p>הצבה בביטוי לצפיפות התערובת נותנת:</p>
<p><span class="math display">\[\rho_{\text{mix}} = \frac{m_{A} + m_{B}}{\frac{m_{A}}{\rho_{A}} + \frac{m_{B}}{\rho_{B}}}\]</span> נגדיר את השברים המסתיים</p>
<p><span class="math display">\[x_{A} = \frac{m_{A}}{m_{A} + m_{B}},x_{B} = \frac{m_{B}}{m_{A} + m_{B}}\]</span> נקבל:</p>
<p><span class="math display">\[\rho_{\text{mix}} = \frac{1}{\frac{x_{A}}{\rho_{A}} + \frac{x_{B}}{\rho_{B}}}\]</span></p>
<div class="callout callout-note definition" title="הגדרה" data-collapse="false">
<p>הצפיפות של תערובת הכוללת <span class="math inline">\(n\)</span> רכיבים שהרכבה נתון על ידי שברים מסתיים</p>
<p><span class="math display">\[\rho_{\text{mix}} = \frac{1}{\sum_{i = 1}^{n}\frac{x_{i}}{\rho_{i}}}\]</span> כאשר <span class="math inline">\(i\)</span> הוא הרכיב, <span class="math inline">\(\rho_{i}\)</span> זו צפיפות הרכיב ו-<span class="math inline">\(x_{i}\)</span> הוא השבר המסתי של הרכיב בתמיסה.</p>
</div>
<p>שתי הדרכים לחישוב צפיפות של תערובת נוזלים נשענות על אותה הנחת עבודה - חיבור נפחים - אך הן מתאימות למצבים שונים. כאשר הרכב התערובת נתון בשברי נפח, החישוב ישיר ואינטואיטיבי, ומתבסס על סכימה משוקללת של צפיפויות הרכיבים. לעומת זאת, כאשר הרכב התערובת נתון בשברי מסה, יש לחשב תחילה את תרומת כל רכיב לנפח הכולל, ולכן מתקבל ביטוי שונה לצפיפות התערובת. חשוב לבחור בדרך החישוב בהתאם לאופן שבו הרכב התערובת נתון, ולא לנסות לערבב בין שתי הגישות. שברי מסה ושברי נפח מתארים תערובות שונות מבחינה פיזיקלית, והחלפה ביניהם ללא חישוב מפורש עלולה להוביל לתוצאה שגויה.</p>
<div class="callout callout-important exercise" title="תרגיל" data-collapse="false">
<p>תערובת נוזלים מורכבת משני רכיבים, A ו-B. צפיפויות הרכיבים הן:</p>
<p><span class="math display">\[\rho_{A} = 800\text{ }kg/m^{3},\rho_{B} = 1200\text{ }kg/m^{3}\]</span></p>
<p>א. חשבו את צפיפות התערובת בהנחת חיבור נפחים, כאשר שברי <u>המסה</u> הם <span class="math inline">\(x_{A} = 0.5\)</span>, <span class="math inline">\(x_{B} = 0.5\)</span>.<br>
ב. חשבו את צפיפות התערובת בהנחת חיבור נפחים, כאשר שברי <u>הנפח</u> הם <span class="math inline">\(\phi_{A} = 0.5\)</span>, <span class="math inline">\(\phi_{B} = 0.5\)</span>.<br>
ג. השוו בין התוצאות והסבירו בקצרה את מקור ההבדל.</p>
<div class="live-exercise">
  <div class="le-row"><span class="le-prompt">א) ρ (שברי מסה) =</span>
    <input class="le-input" type="text" inputmode="decimal" data-answer="960" data-tol="10" placeholder="?" aria-label="צפיפות לפי שברי מסה">
    <span class="le-unit">kg/m³</span></div>
  <div class="le-row"><span class="le-prompt">ב) ρ (שברי נפח) =</span>
    <input class="le-input" type="text" inputmode="decimal" data-answer="1000" data-tol="10" placeholder="?" aria-label="צפיפות לפי שברי נפח">
    <span class="le-unit">kg/m³</span></div>
  <div class="le-actions"><button class="le-check" type="button">בדיקה</button></div>
  <div class="le-feedback" role="status"></div>
  <div class="le-hint">סעיף ג' (הסבר ההבדל) — ראו הפתרון המלא למטה.</div>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled" title="פתרון">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-5-contents" aria-controls="callout-5" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
פתרון
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-5" class="callout-5-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>א. לפי שברי מסה:</p>
<p><span class="math display">\[\rho_{\text{mix}} = \frac{1}{\frac{0.5}{800} + \frac{0.5}{1200}} \approx 960\text{ }kg/m^{3}\]</span></p>
<p>ב. לפי שברי נפח:</p>
<p><span class="math display">\[\rho_{\text{mix}} = 0.5 \cdot 800 + 0.5 \cdot 1200 = 1000\text{ }kg/m^{3}\]</span></p>
<p>ג. התקבלו ערכים שונים משום ששברי מסה ושברי נפח מתארים תערובות שונות מבחינה פיזיקלית. המעבר בין התיאורים תלוי בצפיפויות הרכיבים, ולכן גם תחת אותה הנחת חיבור נפחים מתקבלות תוצאות שונות.</p>
</div>
</div>
</div>
</section>
</section>
<section id="סיכום---צפיפויות-של-נוזלים-וגזים" class="level3" data-number="5.3.3">
<h3 data-number="5.3.3" class="anchored" data-anchor-id="סיכום---צפיפויות-של-נוזלים-וגזים"><span class="header-section-number">5.3.3</span> סיכום - צפיפויות של נוזלים וגזים</h3>
<ul>
<li><p>נוזלים ומוצקים במערכות חד־פאזיות מתאפיינים בנפח כמעט קבוע בתנאי תהליך נתונים.</p></li>
<li><p>הצפיפות היא תכונה פיזיקלית אינטנסיבית, המשמשת לקישור בין נפח לבין כמות חומר (מסה או מולים).</p></li>
<li><p>צפיפות של חומר טהור נקבעת מתוך נתונים ניסיוניים, קורלציות אמפיריות, או מדידה ניסיונית, בהתאם לרמת הדיוק הנדרשת.</p></li>
<li><p>בתערובות נוזלים, הצפיפות תלויה גם בהרכב התערובת ולא רק בזהות הרכיבים.</p></li>
<li><p>חישוב צפיפות של תערובת נוזלים מבוסס לרוב על הנחת חיבור נפחים.</p></li>
<li><p>שברי נפח ושברי מסה אינם שקולים, והחלפה ביניהם ללא חישוב מפורש עלולה להוביל לשגיאה</p></li>
</ul>
</section>
</section>
<section id="גזים-כשהנפח-תלוי-בתנאי-התהליך" class="level2" data-number="5.4">
<h2 data-number="5.4" class="anchored" data-anchor-id="גזים-כשהנפח-תלוי-בתנאי-התהליך"><span class="header-section-number">5.4</span> גזים: כשהנפח תלוי בתנאי התהליך</h2>
<p>צפיפות מוגדרת כיחס בין מסה לנפח. עבור כמות נתונה של חומר, המסה קבועה, ולכן כל שינוי בצפיפות נובע משינוי בנפח. בנוזלים ובמוצקים, שינויי נפח כתוצאה משינויים בלחץ ובטמפרטורה הם קטנים יחסית בטווחי עבודה תעשייתיים, ולכן הצפיפות ניתנת לרוב להתייחסות כקבועה בקירוב. בגזים, לעומת זאת, גם שינוי מתון יחסית בלחץ או בטמפרטורה עלול להוביל לשינוי משמעותי בנפח, ובהתאם גם בצפיפות. מסיבה זו, בגזים אין משמעות לצפיפות ללא ציון מפורש של תנאי התהליך.</p>
<p>אותו גז, באותה כמות חומר, יכול לתפוס נפחים שונים מאוד בלחצים ובטמפרטורות שונות. כתוצאה מכך, הצפיפות של גז אינה תכונה קבועה של החומר בלבד, אלא תלויה באופן ישיר בלחץ ובטמפרטורה שבהם הוא נמצא. כדי לקבוע צפיפות של גז, אין די בידיעת זהות החומר או כמותו - יש צורך גם בקשר המתאר כיצד הנפח משתנה כתלות בתנאי התהליך. משמעות הדבר בהנדסת תהליכים היא שנפח אינו יכול לשמש כמשתנה “שקט” כפי שהיה בנוזלים. כדי לקשר בין תיאורים נפחיים לבין כמויות חומר בגזים, נדרש מודל הקושר בין נפח, טמפרטורה, לחץ וכמות חומר. קשרים כאלה מכונים <strong>משוואות מצב</strong>, משום שהם מתארים את מצב הגז בתנאי תהליך נתונים, ללא תלות במסלול שבו הגיע למצב זה.</p>
<section id="משוואת-הגז-האידיאלי" class="level3" data-number="5.4.1">
<h3 data-number="5.4.1" class="anchored" data-anchor-id="משוואת-הגז-האידיאלי"><span class="header-section-number">5.4.1</span> משוואת הגז האידיאלי</h3>
<p>הקשר הפשוט והנפוץ ביותר לתיאור התנהגות של גזים הוא <strong>משוואת הגז האידיאלי</strong>.</p>
<div class="callout callout-note definition" title="הגדרה" data-collapse="false">
<p>משוואת הגז האידיאלי קושרת בין לחץ, נפח, טמפרטורה וכמות חומר, ומאפשרת לחשב כל אחד מן הגדלים הללו כאשר האחרים ידועים:</p>
<p><span class="math display">\[PV = nRT\]</span></p>
<p>כאשר <span class="math inline">\(P\)</span> הוא הלחץ, <span class="math inline">\(V\)</span> הוא הנפח, <span class="math inline">\(n\)</span>הוא מספר המולים, <span class="math inline">\(T\)</span>היא הטמפרטורה המוחלטת, ו-<span class="math inline">\(R\)</span> הוא קבוע הגזים האוניברסלי. משוואה זו מתארת את מצב הגז בתנאי תהליך נתונים, והיא אינה תלויה בזהות החומר אלא רק בכמותו ובתנאים שבהם הוא נמצא.</p>
</div>
<p>משוואת הגז האידיאלי קושרת בין ארבעה גדלים: לחץ, נפח, טמפרטורה וכמות חומר. משמעות הקשר היא שלמצב הגז אין משתנה אחד “חופשי”: שינוי באחד מן הגדלים מחייב שינוי באחרים. עבור כמות חומר נתונה - אם נקבע את הלחץ והטמפ' אנחנו למעשה מגדירים את הנפח שהגז תופס. אם נשנה את הנפח אחד (או שני) המשתנים האחרים חייבים להשתנות על מנת לאזן את השינוי.</p>
<p>המונח גז אידיאלי אינו מתאר גז שקיים בפועל, אלא מודל תיאורי פשוט להתנהגות של גזים. במודל זה מתקבלות שתי הנחות מרכזיות: נפח המולקולות המרכיבות את הגז זניח ביחס לנפח הכולל, ואין ביניהן אינטראקציות משמעותיות פרט להתנגשויות רגעיות. הנחות אלו מאפשרות לנסח קשר מתמטי פשוט בין תנאי התהליך לבין כמות החומר. המונח “אידיאלי” משקף את העובדה שהמודל אינו מתאר במלואו את ההתנהגות הפיזיקלית של גזים אמיתיים. עם זאת, ברוב היישומים ההנדסיים השגרתיים, שבהם הגזים פועלים בלחצים שאינם גבוהים במיוחד ובטמפרטורות הרחוקות מתנאי עיבוי, ההתנהגות בפועל קרובה מאוד להתנהגות אידיאלית.</p>
<p>משום כך, משוואת הגז האידיאלי משמשת כמודל עבודה ראשון בניתוח תהליכים הכוללים גזים. היא מאפשרת לבצע חישובים נפחיים, לקשר בין מדידות תפעוליות לבין כמויות חומר, ולבנות הבנה תהליכית ברורה לפני שמוסיפים מורכבות. בהמשך נראה כיצד ומתי יש לבחון את תקפות ההנחה האידיאלית, ומה עושים כאשר היא אינה מספקת.</p>
<div class="callout callout-style-simple callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
מעבדה וירטואלית: חקירת תכונות הגז האידיאלי
</div>
</div>
<div class="callout-body-container callout-body">
<p>בסימולציה הבאה נחקור כיצד משתנים מקרוסקופיים (לחץ, נפח, טמפרטורה) קשורים להתנהגות המיקרוסקופית של החלקיקים.</p>
ע<iframe src="https://phet.colorado.edu/sims/html/gas-properties/latest/gas-properties_all.html" width="100%" height="600px" scrolling="no" allowfullscreen=""> </iframe>
<div style="text-align: center; font-size: 0.8em; color: gray;">
<pre><code>מקור: &lt;a href="https://phet.colorado.edu" target="_blank"&gt;PhET Interactive Simulations&lt;/a&gt;, University of Colorado Boulder</code></pre>
</div>
<ol type="1">
<li>קבעו מספר חלקיקים קבוע וטמפרטורה קבועה. מה קורה ללחץ כאשר משנים את נפח הכלי באמצעות הבוכנה? נסו להסביר את התוצאה במונחים של תנועת חלקיקים והתנגשויות בדפנות.<br>
</li>
<li>כעת השאירו את הנפח קבוע והעלו את הטמפרטורה. מה קורה ללחץ? מה השתנה בתנועת החלקיקים ברמה המיקרוסקופית?<br>
</li>
<li>החזירו את הטמפרטורה לערך המקורי, הגדירו טמפרטורה קבועה, והוסיפו חלקיקים למערכת. כיצד משתנה הלחץ כאשר הנפח קבוע? האם התוצאה תלויה בזהות החלקיקים או רק במספרם?<br>
</li>
<li>נסו לשנות שני משתנים בו־זמנית (למשל: הקטנת נפח והורדת טמפרטורה). האם ניתן לצפות מראש את כיוון השינוי בלחץ? מה מקשה על ניבוי אינטואיטיבי במצב כזה?</li>
</ol>
</div>
</div>
<div class="callout callout-important exercise" title="תרגיל" data-collapse="false">
<p>מה יקרה ולמה?</p>
<p>נמקו באופן איכותי (ללא שימוש במספרים) במונחים של לחץ, נפח, טמפרטורה או צפיפות.</p>
<p>א. שקית חטיפים סגורה נארזה בגובה פני הים. במהלך הטיסה, כאשר המטוס מגיע לגובה שיוט, השקית מתנפחת. מה השתנה בתנאי הסביבה שגרם לכך? כיצד השינוי משפיע על נפח הגז שבתוך השקית?</p>
<p>ב. כדור פורח עומד על הקרקע ומחומם באמצעות מבער. בזמן החימום הכדור מתחיל להתרומם, אף על פי שהאוויר שבתוכו זהה בהרכבו לאוויר שמסביב. איזה משתנה תהליכי משתנה בתוך הכדור? כיצד שינוי זה מוביל להתרוממות?</p>
<p>ג. לחץ האוויר בצמיג נמדד בבוקר קר. לאחר נסיעה ארוכה ביום חם, הלחץ בצמיג גבוה יותר. מה גרם לשינוי בלחץ? מדוע נפח הצמיג כמעט ואינו משתנה למרות זאת?</p>
</div>
<div class="callout callout-style-default callout-note callout-titled" title="פתרון">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-7-contents" aria-controls="callout-7" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
פתרון
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-7" class="callout-7-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>א. שקית חטיפים במטוס</p>
<p>השקית נאטמה בגובה פני הים, ולכן כמות הגז שבתוכה קבועה. במהלך העלייה לגובה, לחץ האוויר החיצוני קטן משמעותית. כך שהלחץ בתוך השקית גדול מהלחץ מחוץ לשקית. הגז בתוך השקית מתרחב עד שלחצו משתווה ללחץ הסביבה, ולכן נפח השקית גדל והיא מתנפחת.<br>
זהו תהליך שבו הלחץ החיצוני משתנה, והנפח של הגז מתאים את עצמו לשינוי.</p>
<p>ב. כדור פורח</p>
<p>האוויר בתוך הכדור מחומם, בעוד שהכדור פתוח בתחתיתו ולכן הלחץ בתוכו נשאר קרוב ללחץ האטמוספרי. חימום האוויר מגדיל את נפח האוויר עבור אותה כמות חומר, ולכן צפיפות האוויר בתוך הכדור קטנה. כאשר הצפיפות הממוצעת בתוך הכדור נמוכה מצפיפות האוויר החיצוני, מתקבל כוח עילוי כלפי מעלה.<br>
זהו תהליך שבו הלחץ כמעט קבוע, והשינוי בטמפרטורה מתבטא בשינוי צפיפות.</p>
<p>ג. צמיג רכב ביום חם</p>
<p>במהלך הנסיעה האוויר בצמיג מתחמם עקב חיכוך והעברת חום מהכביש. נפח הצמיג כמעט קבוע, וכמות הגז שבתוכו אינה משתנה. לכן העלייה בטמפרטורה מתבטאת בעלייה בלחץ האוויר בתוך הצמיג.<br>
זהו תהליך שבו הנפח כמעט קבוע, והשינוי בטמפרטורה גורם לשינוי בלחץ.</p>
</div>
</div>
</div>
<section id="קבוע-הגזים-האידיאליים---r" class="level4" data-number="5.4.1.1">
<h4 data-number="5.4.1.1" class="anchored" data-anchor-id="קבוע-הגזים-האידיאליים---r"><span class="header-section-number">5.4.1.1</span> קבוע הגזים האידיאליים - R</h4>
<p>אם נבודד את R מתוך משוואת הגז האידיאלי, נקבל את הביטוי הבא - <span class="math inline">\(R = \frac{PV}{nT}\)</span> משמעות הדבר היא שעבור כל גז אידיאלי בעולם, בכל מצב נתון, היחס בין מכפלת הלחץ והנפח לבין כמות החומר והטמפרטורה הוא <strong>ערך קבוע ובלתי משתנה</strong>. הערך של R משמש למעשה כ"מתרגם" בין שפת הלחץ והנפח שבחרנו לבין שפת האנרגיה והטמפרטורה ולכן הוא תלוי ביחידות בהן אנחנו משתמשים. להלן הערכים הנפוצים ביותר, מסודרים לפי מערכת היחידות של הלחץ והנפח:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;"><strong>מערכת יחידות</strong></th>
<th style="text-align: left;"><strong>לחץ (P)</strong></th>
<th style="text-align: left;"><strong>נפח (V)</strong></th>
<th style="text-align: left;"><strong>טמפ’ (T)</strong></th>
<th style="text-align: left;"><strong>כמות (n)</strong></th>
<th style="text-align: left;"><strong>ערך ה-R</strong></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">מדעית (SI)</td>
<td style="text-align: left;">Pa</td>
<td style="text-align: left;"><span class="math inline">\(m^{3}\)</span></td>
<td style="text-align: left;">K</td>
<td style="text-align: left;"><span class="math inline">\(mol\)</span></td>
<td style="text-align: left;"><span class="math inline">\(8.314 \frac{m^{3} \cdot Pa}{mol \cdot K}\)</span></td>
</tr>
<tr class="even">
<td style="text-align: left;">כימית / אטמוספירות</td>
<td style="text-align: left;">Atm</td>
<td style="text-align: left;">L</td>
<td style="text-align: left;">K</td>
<td style="text-align: left;"><span class="math inline">\(mol\)</span></td>
<td style="text-align: left;"><span class="math inline">\(0.08206 \frac{L \cdot atm}{mol \cdot K}\)</span></td>
</tr>
<tr class="odd">
<td style="text-align: left;">מטרית הנדסית</td>
<td style="text-align: left;">bar</td>
<td style="text-align: left;">L</td>
<td style="text-align: left;">K</td>
<td style="text-align: left;"><span class="math inline">\(mol\)</span></td>
<td style="text-align: left;"><span class="math inline">\(0.08314 \frac{L \cdot bar}{mol \cdot K}\)</span></td>
</tr>
<tr class="even">
<td style="text-align: left;">בריטית (Mechanical)</td>
<td style="text-align: left;">Psi</td>
<td style="text-align: left;"><span class="math inline">\(ft^{3}\)</span></td>
<td style="text-align: left;"><span class="math inline">\(^\circ R\)</span></td>
<td style="text-align: left;"><span class="math inline">\(lb-mol\)</span></td>
<td style="text-align: left;"><span class="math inline">\(10.73 \frac{ft^{3} \cdot psi}{lb-mol \cdot ^\circ R}\)</span></td>
</tr>
</tbody>
</table>
<div class="callout callout-style-default callout-warning callout-titled" title="אזהרה: יחידות מוחלטות בלבד">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
אזהרה: יחידות מוחלטות בלבד
</div>
</div>
<div class="callout-body-container callout-body">
<p>הקבוע R מוגדר עבור סולמות מוחלטים בלבד.</p>
<p><strong>טמפרטורה: </strong>חובה להמיר צלזיוס לקלווין (K) או פרנהייט לרנקין <span class="math inline">\({^\circ}R\)</span></p>
<p><strong>לחץ:</strong> חובה להשתמש בלחץ מוחלט (<span class="math inline">\(P_{abs}\)</span>). אם נתון לחץ יחסי (gauge) יש להוסיף לו את הלחץ האטמוספרי לפני ההצבה במשוואה.</p>
</div>
</div>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
עצה
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>נקודה למחשבה: מה הקשר בין לחץ, נפח ואנרגיה?</strong></p>
<p>עד כה התייחסנו ללחץ ולנפח כאל תכונות פיזיות של הגז. אבל אם נסתכל לעומק על היחידות, נגלה משהו מעניין. במכניקה, אנו יודעים שעבודה (שהיא צורה של אנרגיה) מוגדרת כמכפלה של כוח במרחק:</p>
<p><span class="math display">\[Work = Force \times Distance\quad\lbrack N \cdot m = J\rbrack\]</span></p>
<p>מה קורה כשאנחנו כופלים לחץ בנפח?</p>
<p>לחץ הוא כוח ליחידת שטח (<span class="math inline">\(P = \frac{F}{A}\)</span>) ונפח הוא שטח כפול אורך (<span class="math inline">\(V\  = \ A\  \cdot L\)</span>).</p>
<p><span class="math display">\[P \cdot V = \frac{F}{A} \cdot (A \cdot L) = F \cdot L\]</span></p>
<p>קיבלנו שוב כוח כפול מרחק!</p>
<p>אנו יכולים לראות שיש קשר ישיר בין מכפלת הלחץ והנפח <span class="math inline">\(P\  \cdot V\)</span> לאנרגיה. בהקשר של גזים, ערכים אלו מבטאים את יכולת הגז לבצע עבודה (למשל, לדחוף בוכנה). זו הסיבה שבמערכת היחידות הבינלאומית (SI), הערך של Rנמדד בג'אול (Joule).</p>
</div>
</div>
<div class="callout callout-important exercise" title="תרגיל" data-collapse="false">
<p>השתמשו באחד מערכי R המופיעים בטבלה כאן על מנת למצוא את ערכו של R ביחידות של <span class="math inline">\(\frac{J}{mol\ K}\)</span></p>
<div class="live-exercise">
  <div class="le-row"><span class="le-prompt">R =</span>
    <input class="le-input" type="text" inputmode="decimal" data-answer="8.314" data-tol="0.02" placeholder="?" aria-label="קבוע הגזים">
    <span class="le-unit">J/(mol·K)</span></div>
  <div class="le-actions"><button class="le-check" type="button">בדיקה</button></div>
  <div class="le-feedback" role="status"></div>
  <details class="le-solution"><summary>הצגת פתרון</summary>
    <div class="le-steps">
      <div>מכיוון ש-J = Pa·m³, אפשר לצאת מהערך במערכת SI:</div>
      <div class="le-eq">R = 8.314 Pa·m³/(mol·K) = 8.314 J/(mol·K)</div>
      <div>או להמיר מ-L·atm: 0.08206 L·atm/(mol·K) × 101.325 J/(L·atm) = 8.314 J/(mol·K).</div>
    </div>
  </details>
</div>
</div>
</section>
</section>
<section id="שימוש-במשוואת-הגז-האידיאלי-בחישובים-תהליכיים" class="level3" data-number="5.4.2">
<h3 data-number="5.4.2" class="anchored" data-anchor-id="שימוש-במשוואת-הגז-האידיאלי-בחישובים-תהליכיים"><span class="header-section-number">5.4.2</span> שימוש במשוואת הגז האידיאלי בחישובים תהליכיים</h3>
<p>בהנדסת תהליכים משוואת הגז האידיאלי אינה משמשת לרוב כדי “לחשב לחץ” או “לחשב נפח” באופן מבודד. השימוש המרכזי בה הוא כקשר בין <strong>תיאור נפחי של מערכת</strong> לבין <strong>כמות החומר שבה</strong>. במערכות גזיות, מדידות תפעוליות ניתנות בדרך כלל במונחים של לחץ, טמפ' ונפח או ספיקה נפחית, אך מאזני החומר נכתבים תמיד על כמות החומר (במסה או במולים). משוואת הגז האידיאלי מאפשרת מעבר מהיר בין הערכים.</p>
<ul>
<li><strong>נפח מולרי של גז בתנאים סטנדרטיים (STP/SATP)</strong></li>
</ul>
<p>בהנדסה ובמדעים נהוג להגדיר "תנאים סטנדרטיים" כדי לאפשר השוואה נוחה בין נתונים. כפי שציינו קודם, קיימים שני תקנים נפוצים: STP - <span class="math inline">\(0^{\circ}C,1\text{ atm}\)</span>, ו- SATP - <span class="math inline">\(25^{\circ}C,1\text{ bar}\)</span>.</p>
<p>מכיוון שבמודל הגז האידיאלי הנפח תלוי אך ורק בT, P ו- n עבור כמות קבועה של 1 מול גז, הנפח יהיה זהה תמיד בכל אחד מהתנאים הללו. לכן, ניתן לחשב מראש את "הנפח המולרי הסטנדרטי" ולהשתמש בו כנתון קבוע לקיצור חישובים:</p>
<div class="callout callout-note definition" title="הגדרה" data-collapse="false">
<ul>
<li>עבור STP (<span class="math inline">\(0^{\circ}C,1\text{ atm}\)</span>):</li>
</ul>
<p><span class="math display">\[\widehat{V} = \frac{RT}{P} = \frac{0.08206\frac{L \cdot atm}{mol \cdot K} \cdot 273.15K}{1\text{ atm}} \approx 22.4\frac{L}{mol}\]</span></p>
<ul>
<li>עבור SATP (<span class="math inline">\(25^{\circ}C,1\text{ bar}\)</span>):</li>
</ul>
<p><span class="math display">\[\widehat{V} = \frac{RT}{P} = \frac{0.08314\frac{L \cdot bar}{mol \cdot K} \cdot 298.15K}{1\text{ bar}} \approx 24.8\frac{L}{mol}\]</span></p>
<p>(הערה - שימו לב איזה ערך של R נמצא בכל חישוב).</p>
</div>
<p>מאחר ואלו ותנאים אלו קבועים, במקום להציב בכל פעם במשוואת המצב המלאה, אם ידוע שהגז נמצא בתנאי STP, ניתן להמיר מיידית בין מולים לנפח באמצעות היחס הקבוע של <span class="math inline">\({\widehat{V}}_{Ideal,STP} = 22.4\text{ L/mol}\)</span>.</p>
<p>ובתנאי SATP ניתן להמיר מיידית <span class="math inline">\({\widehat{V}}_{Ideal,SATP} = 24.8\text{ L/mol}\)</span></p>
<div class="callout callout-important exercise" title="תרגיל" data-collapse="false">
<p>זרם של גז אידיאלי זורם בספיקה מולרית של <span class="math inline">\(100\ \frac{mol}{h}\)</span>.</p>
<p>חשבו את הספיקה הנפחית: א. בתנאי STP (<span class="math inline">\(0^\circ C\)</span>, 1 atm). ב. בתנאי SATP (<span class="math inline">\(25^\circ C\)</span>, 1 bar).</p>
<div class="live-exercise">
  <div class="le-row"><span class="le-prompt">א) V̇ (STP) =</span>
    <input class="le-input" type="text" inputmode="decimal" data-answer="2240" data-tol="25" placeholder="?" aria-label="ספיקה נפחית STP">
    <span class="le-unit">L/h</span></div>
  <div class="le-row"><span class="le-prompt">ב) V̇ (SATP) =</span>
    <input class="le-input" type="text" inputmode="decimal" data-answer="2480" data-tol="25" placeholder="?" aria-label="ספיקה נפחית SATP">
    <span class="le-unit">L/h</span></div>
  <div class="le-actions"><button class="le-check" type="button">בדיקה</button></div>
  <div class="le-feedback" role="status"></div>
  <details class="le-solution"><summary>הצגת פתרון</summary>
    <div class="le-steps">
      <div>משתמשים בנפח המולרי הסטנדרטי הקבוע (מכפילים בספיקה):</div>
      <div class="le-eq">א) STP: 100 · 22.4 = 2240 L/h</div>
      <div class="le-eq">ב) SATP: 100 · 24.8 = 2480 L/h</div>
    </div>
  </details>
</div>
</div>
<ul>
<li><strong>חישוב כמות גז מנפח נתון</strong></li>
</ul>
<p>כאשר ידועים הלחץ, הטמפרטורה והנפח של גז, ניתן לחשב את כמות החומר שבו באמצעות:</p>
<p><span class="math display">\[n = \frac{PV}{RT}\]</span> זהו שימוש בסיסי ונפוץ, למשל לצורך חישוב כמה מולים של גז נמצאים במיכל, או לקביעת כמות גז שאוחסנה בנפח נתון בתנאי תהליך ידועים.</p>
<ul>
<li><strong>מעבר מספיקה נפחית לספיקה מולרית</strong></li>
</ul>
<p>בתהליכים רציפים, הנתון התפעולי השכיח הוא <strong>ספיקה נפחית</strong> (<span class="math inline">\(\dot{V}\)</span>), בעוד שמאזני חומר דורשים <strong>ספיקה מולרית</strong> (<span class="math inline">\(\dot{n}\)</span>). משוואת הגז האידיאלי מאפשרת לקשר בין השתיים:</p>
<p><span class="math display">\[\dot{n} = \frac{P\dot{V}}{RT}\]</span></p>
<ul>
<li><strong>שימוש ביחסים בין מצבים</strong></li>
</ul>
<p>לעיתים אין צורך בקבוע <span class="math inline">\(R\)</span> כלל. כאשר כמות הגז קבועה, ניתן להשוות בין שני מצבים של אותו גז:</p>
<p><span class="math display">\[\frac{P_{1}V_{1}}{T_{1}} = \frac{P_{2}V_{2}}{T_{2}}\]</span> במקרים רבים נשתמש במשוואות מהסוג הזה כדי להבין איך שינוי בלחץ או בטמפ' משפיע על הנפח ואיך תנאי התהליך משפיעים על הגז שבתוך התהליך, במיוחד כשאנו לא יודעים את כמות הגז המוחלט.</p>
<p>לפני כל הצבה במשוואת הגז האידיאלי, נשאל את עצמנו - מהי המערכת? מה ידוע ונמדד? מה קבוע ומה משתנה? האם מדובר במצב אחד או בהשוואה בין מצבים?</p>
<div class="callout callout-important exercise" title="תרגיל" data-collapse="false">
<p>חנקן מולקולרי כלוא במיכל בנפח <span class="math inline">\(1.5\text{ }m^{3}\)</span>.הלחץ במיכל הוא <span class="math inline">\(150\text{ }kPa\)</span> והטמפרטורה היא <span class="math inline">\(300\text{ }K\)</span>. מהי כמות הגז במיכל? אם היינו מחליפים את הגז למימן - האם הכמות היתה משתנה?</p>
<div class="live-exercise">
  <div class="le-row"><span class="le-prompt">n =</span>
    <input class="le-input" type="text" inputmode="decimal" data-answer="0.090" data-tol="0.003" placeholder="?" aria-label="כמות הגז">
    <span class="le-unit">kmol</span></div>
  <div class="le-actions"><button class="le-check" type="button">בדיקה</button></div>
  <div class="le-feedback" role="status"></div>
  <div class="le-hint">החלק על המימן (רעיוני) — ראו הפתרון המלא למטה.</div>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled" title="פתרון">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-10-contents" aria-controls="callout-10" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
פתרון
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-10" class="callout-10-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>נתון:<br>
<span class="math display">\[V = 1.5\text{ }m^{3}\ \ \ \ \ ,\ \ \ \ \ P = 150\text{ }kPa\ \ \ \ \ ,\ \ \ \ \ T = 300K\]</span></p>
<p>נשתמש במשוואת הגז האידיאלי בצורתה הישירה:</p>
<p><span class="math display">\[n = \frac{PV}{RT} = \frac{150\text{ }kPa*1.5\text{ }m^{3}}{300K*8.314\frac{J}{mol\ K}} = \frac{150\frac{\text{ }kN}{m^{2}}*1.5\text{ }m^{3}}{300K*8.314\frac{N*m}{mol\ K}} = 0.090\ kmol\]</span></p>
</div>
</div>
</div>
<div class="callout callout-important exercise" title="תרגיל" data-collapse="false">
<p>מיכל סגור ובעל נפח קבוע מכיל גז אידיאלי.<br>
במצב ההתחלתי לחץ הגז הוא <span class="math inline">\(100\text{ }kPa\)</span> והטמפרטורה היא <span class="math inline">\(300\text{ }K\)</span>. המיכל מחומם עד שטמפרטורת הגז עולה ל־<span class="math inline">\(450\text{ }K\)</span>. מהו הלחץ במצב הסופי?</p>
<div class="live-exercise">
  <div class="le-row"><span class="le-prompt">P₂ =</span>
    <input class="le-input" type="text" inputmode="decimal" data-answer="150" data-tol="3" placeholder="?" aria-label="לחץ סופי">
    <span class="le-unit">kPa</span></div>
  <div class="le-actions"><button class="le-check" type="button">בדיקה</button></div>
  <div class="le-feedback" role="status"></div>
  <details class="le-solution"><summary>הצגת פתרון</summary>
    <div class="le-steps">
      <div>הנפח וכמות הגז קבועים, ולכן P/T קבוע (חוק גה-ליסאק):</div>
      <div class="le-eq">P₁/T₁ = P₂/T₂ → P₂ = P₁·(T₂/T₁)</div>
      <div class="le-eq">P₂ = 100 · (450/300) = 150 kPa</div>
      <div>הטמפרטורות כבר בקלווין — חובה תמיד להשתמש בטמפרטורה אבסולוטית.</div>
    </div>
  </details>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled" title="פתרון">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-11-contents" aria-controls="callout-11" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
פתרון
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-11" class="callout-11-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>נתון:<br>
<span class="math display">\[P_{1} = 100\text{ }kPa\ \ \ \ ;\ \ \ \ \ T_{1} = 300\ K\ \ \ \ \ \ \ \ ;\ \ \ \ \ \ T_{2} = 450\ K\]</span> המיכל קשיח וסגור - נפח וכמות הגז קבועים.<br>
לפני החישוב, העריכו - האם אנו מצפים שהלחץ יעלה או ירד?</p>
<p>אנו לא יודעים את הנפח, אבל אנחנו יודעים שהנפח ומספר המולים קבוע</p>
<p>התחלה - <span class="math inline">\(P_{1}V = nRT_{1}\)</span> סיום <span class="math inline">\(P_{2}V = nRT_{2}\)</span></p>
<p>נחלק בין המשוואות</p>
<p><span class="math display">\[\frac{P_{1}V}{P_{2}V} = \frac{nRT_{1}}{nRT_{2}}\]</span></p>
<p>ולאחר צמצום הקבועים קיבלנו</p>
<p><span class="math display">\[\frac{P_{1}}{T_{1}} = \frac{P_{2}}{T_{2}}\ \ \ \  = &gt; \ \ \ \ \ P_{2} = P_{1}\frac{T_{2}}{T_{1}}\ \ \ \ \ \ \]</span> נזכור כי משוואת הגזים האידיאליים מתייחסת לטמפרטורה אבסולוטית (קלווין). כאן הנתונים כבר נתונים בקלווין, אך אילו היו נתונים בצלזיוס היה חובה להמיר לקלווין לפני ההצבה.</p>
<p><span class="math display">\[P_{2} = 100kPa \cdot \frac{450\ K}{300\ K} = 150kPa\]</span></p>
</div>
</div>
</div>
</section>
<section id="מתי-מותר-להניח-שהגז-אידיאלי-קריטריון-האידיאליות" class="level3" data-number="5.4.3">
<h3 data-number="5.4.3" class="anchored" data-anchor-id="מתי-מותר-להניח-שהגז-אידיאלי-קריטריון-האידיאליות"><span class="header-section-number">5.4.3</span> מתי מותר להניח שהגז אידיאלי? (קריטריון האידיאליות)</h3>
<p>משוואת הגז האידיאלי היא כלי נוח ופשוט, אך כפי שציינו, היא מזניחה את הנפח העצמי של המולקולות ואת כוחות המשיכה/דחייה ביניהן. לכן, לפני שנשתמש בה לתכנון תהליך, עלינו לוודא שאנחנו נמצאים בתחום שבו ההזנחות האלו מוצדקות.</p>
<p>מבחינה פיסיקלית המודל האידיאלי עובד היטב כאשר המולקולות "רחוקות" זו מזו.</p>
<ol type="1">
<li><p>לחץ נמוך: בלחצים נמוכים יחסית הצפיפות נמוכה והמרחק הממוצע בין המולקולות גדול.</p></li>
<li><p>טמפרטורה גבוהה: כשהטמפרטורה גבוהה, האנרגיה הקינטית של המולקולות גבוהה מאוד ביחס לכוחות המשיכה ביניהן, והן "מתעלמות" זו מזו.</p></li>
</ol>
<p>אך מה נחשב "לחץ נמוך מספיק"? ומהי "טמפרטורה גבוהה מספיק"? ואיך התלות בינהם משפיעה על ההחלטה? לשם כך אנו זקוקים לקריטריון כמותי.</p>
<p>כלל האצבע עבור הנחת גזים אידיאליים מבוסס על הנפח הסגולי המולרי</p>
<p>בהנדסת תהליכים נהוג להשתמש ב"כלל אצבע" המבוסס על הנפח הסגולי המולרי (<span class="math inline">\(\widehat{V}\)</span>) שהגז תופס. ככל שהנפח המולרי גדול יותר, כך המולקולות רחוקות יותר זו מזו וההתנהגות קרובה יותר לאידיאלית.</p>
<p>הקריטריון מתחלק לשני סוגי גזים:</p>
<div class="callout callout-note definition" title="הגדרה" data-collapse="false">
<ol type="1">
<li>עבור גזים פשוטים (דו-אטומיים ואצילים):</li>
</ol>
<p>גזים כמו חנקן (<span class="math inline">\(N_{2}\)</span>), חמצן (<span class="math inline">\(O_{2}\)</span>), ומימן (<span class="math inline">\(H_{2}\)</span>) הם בעלי מולקולות קטנות יחסית ואינטראקציות חלשות. עבורם ניתן להניח התנהגות אידיאלית כאשר:</p>
<p><span class="math display">\[{\widehat{V}}_{ideal} = \frac{RT}{P} \geq 5\frac{L}{mol}\ \ \ \ \ or\ \ \ {\widehat{V}}_{ideal} = \frac{RT}{P} \geq 80\frac{ft^{3}}{lbmol}\]</span></p>
<ol start="2" type="1">
<li>עבור גזים אחרים (מורכבים):</li>
</ol>
<p>גזים כמו פחמן דו-חמצני (<span class="math inline">\(CO_{2}\)</span>), אדי מים או פחמימנים, הם בעלי מולקולות גדולות יותר או בעלי קוטביות חזקה יותר. עבורם נדרש "מרחב מחייה" גדול יותר כדי להתנהג באופן אידיאלי:</p>
<p><span class="math display">\[\ \ {\widehat{V}}_{ideal} = \frac{RT}{P} \geq 20\frac{L}{mol}\ \ \ \ \ {\widehat{V}}_{ideal} = \frac{RT}{P} \geq 320\frac{ft^{3}}{lbmol}\]</span></p>
</div>
<div class="callout callout-example example" title="דוגמה" data-collapse="false">
<p>הסטודנטית החרוצה סתוונית היא מהנדסת תהליך במפעל כימי. במחסן הציוד נמצא מיכל לחץ ישן בנפח 500L, על המיכל מוטבע לחץ העבודה המקסימלי המותר 60bar. מנהל הייצור רוצה לדחוס לתוך המיכל 35kg של גז חנקן (<span class="math inline">\(N_{2}\)</span>) ולאחסן אותו בחצר המפעל, שם הטמפרטורה ביום חם עלולה להגיע ל<span class="math inline">\(45^{\circ}C\)</span>.</p>
<p>חשבי את הלחץ שיווצר במיכל בתנאים אלו, תחת הנחת גז אידיאלי. האם המיכל יעמוד בלחץ? האם השימוש במשוואת הגז האידיאלי היה מוצדק במקרה זה?</p>
<p>חלק א': חישוב הלחץ</p>
<p>לפני שנציב במשוואה <span class="math inline">\(P = \frac{nRT}{V}\)</span>, עלינו לסדר את היחידות.</p>
<p>חישוב המולים (<span class="math inline">\(n\)</span>)</p>
<p><span class="math display">\[n = \frac{35,000\, g}{28\, g\text{/}mol} = 1,250\, mol\]</span></p>
<p>סידור הטמפרטורה והנפח:</p>
<p><span class="math display">\[T\  = \ 45\  + \ 273.15\  = \ 318.15\,\ K\]</span></p>
<p><span class="math display">\[V\  = \ 500\ \, L\]</span></p>
<p>אנחנו רוצים לחץ ב-bar, ויש לנו נפח ב-L. ולכן <span class="math inline">\(R = 0.08314\frac{bar \cdot L}{mol \cdot K}\)</span></p>
<p>הצבה:</p>
<p><span class="math display">\[P = \frac{1,250mol \cdot 0.08314\frac{bar \cdot L}{mol \cdot K} \cdot 318K}{500L} = 66\, bar\]</span></p>
<p>הלחץ המחושב (<span class="math inline">\(66.13\ \,\ bar\)</span>) גבוה מהלחץ המותר (<span class="math inline">\(60\ \,\ bar\)</span>). המיכל מסוכן לשימוש!</p>
<p>אבל האם זה נכון להתבסס על המספר שחישבנו (<span class="math inline">\(66bar\)</span>) בכלל נכון? בואי נבדוק את "כלל האצבע" לאידיאליות. נחשב את הנפח המולרי (<span class="math inline">\(\widehat{V}\)</span>) שיש לגז בתוך המיכל:</p>
<p><span class="math display">\[\widehat{V} = \frac{V}{n} = \frac{500\, L}{1,250\, mol} = 0.4\,\frac{L}{mol}\]</span></p>
<p>הבדיקה:</p>
<p>הכלל עבור גזים דו-אטומיים (כמו חנקן) דורש <span class="math inline">\(\widehat{V} \geq 5\, L\text{/}mol\)</span></p>
<p>אבל הערך שקיבלנו נמוך משמעותית. מה זה אומר?</p>
<p>המשמעות היא שאנחנו נמצאים עמוק בתוך התחום הלא-אידיאלי. המולקולות צפופות מאוד. החישוב שעשינו בחלק א' הוא בעל שגיאה גדולה מאוד (סביר להניח שהלחץ האמיתי יהיה אפילו גבוה יותר בגלל נפח המולקולות עצמן שתופס מקום). כך שלא רק שהמיכל מסוכן לפי החישוב, אלא שהמצב בפועל כנראה חמור יותר. אסור להשתמש במשוואת הגז האידיאלי לתכנון כאן.</p>
</div>
<div class="callout callout-important exercise" title="תרגיל" data-collapse="false">
<p>גז חנקן (<span class="math inline">\(N_2\)</span>, גז פשוט) נמצא בטמפרטורה <span class="math inline">\(T = 300\ K\)</span>. בדקו האם מותר להניח התנהגות אידיאלית בכל אחד מהמצבים, לפי קריטריון הנפח המולרי (לגז פשוט: <span class="math inline">\(\widehat{V} \geq 5\ L/mol\)</span>).</p>
<p>חשבו את הנפח המולרי האידיאלי <span class="math inline">\(\widehat{V} = RT/P\)</span>: א. בלחץ <span class="math inline">\(P = 2\ atm\)</span>. ב. בלחץ <span class="math inline">\(P = 30\ atm\)</span>.</p>
<div class="live-exercise">
  <div class="le-row"><span class="le-prompt">א) V̂ (2 atm) =</span>
    <input class="le-input" type="text" inputmode="decimal" data-answer="12.3" data-tol="0.3" placeholder="?" aria-label="נפח מולרי ב-2 atm">
    <span class="le-unit">L/mol</span></div>
  <div class="le-row"><span class="le-prompt">ב) V̂ (30 atm) =</span>
    <input class="le-input" type="text" inputmode="decimal" data-answer="0.82" data-tol="0.05" placeholder="?" aria-label="נפח מולרי ב-30 atm">
    <span class="le-unit">L/mol</span></div>
  <div class="le-actions"><button class="le-check" type="button">בדיקה</button></div>
  <div class="le-feedback" role="status"></div>
  <details class="le-solution"><summary>הצגת פתרון</summary>
    <div class="le-steps">
      <div>מחשבים V̂ = RT/P (עם R = 0.08206 L·atm/mol·K) ומשווים לסף 5 L/mol:</div>
      <div class="le-eq">א) V̂ = 0.08206 · 300 / 2 = 12.3 L/mol ≥ 5 → מותר להניח גז אידיאלי ✓</div>
      <div class="le-eq">ב) V̂ = 0.08206 · 300 / 30 = 0.82 L/mol &lt; 5 → אסור! צריך שיטות גז ריאלי (Z / EOS)</div>
      <div>המסקנה: לחץ גבוה מקרב את המולקולות — ההנחה האידיאלית קורסת.</div>
    </div>
  </details>
</div>
</div>
</section>
<section id="תערובות-של-גזים-אידיאליים" class="level3" data-number="5.4.4">
<h3 data-number="5.4.4" class="anchored" data-anchor-id="תערובות-של-גזים-אידיאליים"><span class="header-section-number">5.4.4</span> תערובות של גזים אידיאליים</h3>
<p>ברוב היישומים ההנדסיים אנו עוסקים בתערובות של גזים ולא בחומרים טהורים. האוויר שאנו נושמים, הגז הטבעי שאנו שורפים והעשן הנפלט מארובות - כולם תערובות. היתרון במודל הגז האידיאלי הוא שניתן להתייחס לתערובת כאל אוסף של חלקיקים עצמאיים. מכיוון שהמולקולות אינן משפיעות זו על זו, כל רכיב בתערובת מתנהג כאילו הוא נמצא שם לבד.</p>
<p><u>חוק דלטון (Dalton) - חיבור לחצים</u></p>
<p>ג'ון דלטון ניסח עיקרון פשוט אך חזק: במיכל בנפח קבוע ובטמפרטורה קבועה, הלחץ הכולל של תערובת גזים שווה לסכום הלחצים שכל גז היה מפעיל אילו היה תופס את <strong>כל הנפח לבדו</strong>.</p>
<p>הלחץ הזה, שכל גז תורם בנפרד, נקרא <strong>לחץ חלקי</strong> (<span class="math inline">\(P_{i}\)</span>).</p>
<p><span class="math display">\[P_{total} = P_{A} + P_{B} + P_{C} + \ldots = \sum_{}^{}P_{i}\]</span></p>
<p>עבור גזים אידיאליים, קיים קשר ישיר בין השבר המולי ללחץ החלקי:</p>
<p><span class="math display">\[P_{i} = y_{i} \cdot P_{total}\]</span></p>
<p><u>חוק אמגא (Amagat) - חיבור נפחים</u></p>
<p>בעוד דלטון מסתכל על נפח קבוע ולחצים משתנים, אמגא (Amagat) מסתכל על המצב ההפוך: מה היה קורה אילו היינו מפרידים את הגזים כך שכל אחד יהיה בלחץ המקורי של התערובת (<span class="math inline">\(P_{total}\)</span>) ובטמפרטורה המקורית?</p>
<p>במצב זה, הנפח הכולל הוא סכום הנפחים שכל גז תופס בנפרד:</p>
<p><span class="math display">\[V_{total} = V_{A} + V_{B} + V_{C} + \ldots = \sum_{}^{}V_{i}\]</span></p>
<p>עבור גזים אידיאליים, הקשר הוא:</p>
<p><span class="math display">\[V_{i} = y_{i} \cdot V_{total}\]</span></p>
<p>גדלים אלו משמשים אותנו לרוב להגדרת הרכב באחוזים נפחיים (<span class="math inline">\(\% v\text{/}v\)</span>), צורת הביטוי הנפוצה ביותר לאנליזות גז (כרומטוגרפיה, מפרטי בטיחות ועוד).</p>
<p><img src="images\IntroToCHemEng2/media/image79.png" class="img-fluid"></p>
<p>מהחוקים הללו נגזרת אחת התכונות השימושיות ביותר של גזים אידיאלים - הזהות המוחלטת בין יחסי המולים, הלחצים והנפחים.</p>
<div class="callout callout-note definition" title="הגדרה" data-collapse="false">
<p>עבור גז <u>אידיאלי</u> מתקיים תמיד:</p>
<p><span class="math display">\[y_{i} = \frac{n_{i}}{n_{total}} = \frac{P_{i}}{P_{total}} = \frac{V_{i}}{V_{total}}\]</span></p>
</div>
<p>כך שאם נתון לנו הרכב של גז ב"אחוזים נפחיים" (למשל: אוויר מכיל 21% חמצן), ניתן להניח מיד שזהו גם אחוז המולים, וזהו גם אחוז הלחץ שהגז תורם.</p>
<div class="callout callout-style-default callout-note callout-titled" title="הערה חשובה">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
הערה חשובה
</div>
</div>
<div class="callout-body-container callout-body">
<p>זהות זו נכונה רק עבור גזים אידיאליים. בגזים ריאליים בלחצים גבוהים, אחוזי הנפח אינם זהים בהכרח לאחוזי המולים עקב כוחות דחייה ומשיכה שונים בין מולקולות שונות (נפח הערבוב אינו זניח).</p>
</div>
</div>
<div class="callout callout-important exercise" title="תרגיל" data-collapse="false">
<p>תערובת גזים אידיאלית נמצאת בלחץ כולל <span class="math inline">\(P_{total} = 4\ atm\)</span>. ההרכב המולרי: 25% <span class="math inline">\(O_2\)</span>, 60% <span class="math inline">\(N_2\)</span>, 15% <span class="math inline">\(CO_2\)</span>.</p>
<p>חשבו את הלחץ החלקי של כל רכיב.</p>
<div class="live-exercise">
  <div class="le-row"><span class="le-prompt">P(O₂) =</span>
    <input class="le-input" type="text" inputmode="decimal" data-answer="1.0" data-tol="0.05" placeholder="?" aria-label="לחץ חלקי חמצן">
    <span class="le-unit">atm</span></div>
  <div class="le-row"><span class="le-prompt">P(N₂) =</span>
    <input class="le-input" type="text" inputmode="decimal" data-answer="2.4" data-tol="0.05" placeholder="?" aria-label="לחץ חלקי חנקן">
    <span class="le-unit">atm</span></div>
  <div class="le-row"><span class="le-prompt">P(CO₂) =</span>
    <input class="le-input" type="text" inputmode="decimal" data-answer="0.6" data-tol="0.05" placeholder="?" aria-label="לחץ חלקי פחמן דו-חמצני">
    <span class="le-unit">atm</span></div>
  <div class="le-actions"><button class="le-check" type="button">בדיקה</button></div>
  <div class="le-feedback" role="status"></div>
  <details class="le-solution"><summary>הצגת פתרון</summary>
    <div class="le-steps">
      <div>לפי חוק דלטון, הלחץ החלקי = השבר המולי × הלחץ הכולל:</div>
      <div class="le-eq">P(O₂) = 0.25 · 4 = 1.0 atm</div>
      <div class="le-eq">P(N₂) = 0.60 · 4 = 2.4 atm</div>
      <div class="le-eq">P(CO₂) = 0.15 · 4 = 0.6 atm</div>
      <div>בדיקה: 1.0 + 2.4 + 0.6 = 4.0 atm = P_total ✓</div>
    </div>
  </details>
</div>
</div>
</section>
<section id="סיכום---גזים-אידיאליים" class="level3" data-number="5.4.5">
<h3 data-number="5.4.5" class="anchored" data-anchor-id="סיכום---גזים-אידיאליים"><span class="header-section-number">5.4.5</span> סיכום - גזים אידיאליים</h3>
<ul>
<li><p>גז אידיאלי הוא מודל תיאורטי המתבסס על ההנחותש נפח המולקולות ואינטראקציות ביניהן מוזנחים. המודל אינו מדויק לחלוטין אך מתאים לרוב היישומים ההנדסיים בלחצים לא גבוהים ובטמפרטורות רחוקות מתנאי עיבוי.</p></li>
<li><p>משוואת הגז האידיאלי:</p></li>
</ul>
<p><span class="math display">\[PV = nRT\]</span> קושרת בין לחץ P, נפח <span class="math inline">\(V\)</span>, טמפרטורה מוחלטת <span class="math inline">\(T\)</span> וכמות חומר <span class="math inline">\(n\)</span>. שינוי באחד מחייב שינוי באחרים בהתאם לאילוצי המערכת.</p>
<ul>
<li>קבוע הגזים:</li>
</ul>
<p><span class="math display">\[R = \frac{PV}{nT} = 8.314\frac{m^{3}\ Pa}{mol\ K} = \ 0.08206\ \frac{L\ atm}{mol\ K} = 10.73\frac{ft^{3}\ psi}{lb - mol\ \ {^\circ}R}\]</span></p>
<p>הוא יחס פיזיקלי קבוע; ערכו הנומרי תלוי במערכת היחידות. בשימוש בו אנו חייבים להשתמש בטמפרטורה מוחלטת (K או <span class="math inline">\({^\circ}R\)</span> (ובלחץ מוחלט.</p>
<ul>
<li><strong>שימושים מרכזיים בהנדסת תהליכים:</strong>
<ul>
<li>כמות גז ממיכל: <span class="math display">\[n = \frac{PV}{RT}\]</span></li>
<li>מעבר מספיקה נפחית לספיקה מולרית: <span class="math display">\[\dot{n} = \frac{P\dot{V}}{RT}\]</span></li>
<li>השוואה בין מצבים (<span class="math inline">\(n\)</span> קבוע): <span class="math display">\[\frac{P_{1}V_{1}}{T_{1}} = \frac{P_{2}V_{2}}{T_{2}}\]</span></li>
</ul></li>
<li>ניתן לבדוק את תקפות ההנחה האידיאלית נבחנת לפי מידת הדילול של הגז. נפח מולרי אידיאלי:</li>
</ul>
<p><span class="math display">\[\widehat{V} = \frac{RT}{P}\]</span></p>
<ol type="1">
<li>עבור גזים פשוטים (דו-אטומיים ואצילים):</li>
</ol>
<p><span class="math display">\[{\widehat{V}}_{ideal} = \frac{RT}{P} \geq 5\frac{L}{mol}\ \ \ \ \ or\ \ \ {\widehat{V}}_{ideal} = \frac{RT}{P} \geq 80\frac{ft^{3}}{lbmol}\]</span></p>
<ol start="2" type="1">
<li>עבור גזים אחרים (מורכבים):</li>
</ol>
<p><span class="math display">\[\ \ {\widehat{V}}_{ideal} = \frac{RT}{P} \geq 20\frac{L}{mol}\ \ \ \ \ {\widehat{V}}_{ideal} = \frac{RT}{P} \geq 320\frac{ft^{3}}{lbmol}\]</span></p>
<ul>
<li>בתערובות של גזים אידיאליים כל רכיב מתנהג באופן עצמאי: לפי חוק דלתון הלחץ הכולל הוא סכום הלחצים החלקיים, ולפי חוק אמגא הנפח הכולל הוא סכום הנפחים החלקיים.<br>
</li>
<li>באופן כללי כשאנחנו עובדים עם תערובות של גזים אידיאליים אפשר לראות שהשבר המולי שווה לשבר הנפחי ושווה לשבר הלחצים, וניתן לעשות מעבר זה באופן אוטומטי. ** <span class="math display">\[y_{i} = \frac{n_{i}}{n_{total}} = \frac{P_{i}}{P_{total}} = \frac{V_{i}}{V_{total}}\]</span></li>
</ul>
</section>
</section>
<section id="גזים-ריאליים" class="level2" data-number="5.5">
<h2 data-number="5.5" class="anchored" data-anchor-id="גזים-ריאליים"><span class="header-section-number">5.5</span> גזים ריאליים</h2>
<p>עד כה ניתחנו מערכות גזיות תוך שימוש במשוואת הגז האידיאלי <span class="math inline">\(PV = nRT\)</span> אשר סיפקה תיאור פשוט ואפקטיבי של הקשר בין לחץ, נפח, טמפרטורה וכמות חומר. כאשר אנו עובדים על לחצים מתונים וטמפרטורות שאינן קיצוניות חישוב זה נותן לנו הערכה טובה ומאפשר חישוב מהיר ואינטואיטיבי של משתני תהליך. עם זאת, ככל שתנאי התהליך מתרחקים מאזורים אלו, ובפרט בלחצים גבוהים או בטמפרטורות נמוכות, ההתנהגות של גזים מתחילה לסטות מן האידיאליות. במצבים אלו, ההנחות הבסיסיות של המודל האידיאלי, נפח זניח של המולקולות והיעדר אינטראקציות ביניהן, אינן מתקיימות עוד, והשימוש במשוואת הגז האידיאלי עלול להוביל לשגיאות חישוביות שאינן זניחות מבחינה הנדסית.</p>
<p>כאשר מתברר שמשוואת הגז האידיאלי אינה מספקת תוצאות מדויקות, עומדות לרשותנו שתי אפשרויות עיקריות לפתרון. האפשרות הראשונה היא <strong>שימוש במשוואות מצב מתקדמות</strong> - מודלים מתמטיים מורכבים יותר (תיאורטיים או אמפיריים) שנועדו להחליף את המשוואה הפשוטה ולתאר בדיוק רב את פיזיקת החלקיקים. האפשרות השנייה, והנפוצה מאוד בהנדסה, היא <strong>תיקון המודל הקיים.</strong> במקום לעבור למשוואה חדשה ומסובכת, אנו שומרים על התבנית המוכרת והנוחה של משוואת הגז האידיאלי, אך מוסיפים לה 'גורם תיקון' המפצה על הסטייה מההתנהגות האידיאלית. בפרק זה נתחיל ביישום שיטת התיקון (מקדם הדחיסות), ובהמשך נכיר את המודלים המתקדמים יותר לתיאור גזים ריאליים.</p>
<section id="מקדם-הדחיסות-z" class="level3" data-number="5.5.1">
<h3 data-number="5.5.1" class="anchored" data-anchor-id="מקדם-הדחיסות-z"><span class="header-section-number">5.5.1</span> מקדם הדחיסות Z</h3>
<p>כדי להתמודד עם סטיות מהתנהגות אידיאלית של גזים, נרצה תחילה להרחיב את משוואת הגז האידיאלי מבלי לנטוש אותה לחלוטין. הדרך הפשוטה והישירה לעשות זאת היא להכניס גורם תיקון המתאר את הפער בין ההתנהגות האידיאלית לבין ההתנהגות הנמדדת בפועל. גורם תיקון זה נקרא מקדם הדחיסות, ומסומן <span class="math inline">\(Z\)</span>.</p>
<div class="callout callout-note definition" title="הגדרה" data-collapse="false">
<p>מקדם הדחיסות מוגדר כיחס בין הנפח המולרי האמיתי של הגז (<span class="math inline">\({\widehat{V}}_{real}\)</span>), לבין הנפח שהיה מתקבל אילו הגז היה מתנהג כאידיאלי באותם תנאי לחץ וטמפרטורה (<span class="math inline">\({\widehat{V}}_{ideal} = RT\text{/}P\)</span>)</p>
<p><span class="math display">\[Z = \frac{{\widehat{V}}_{real}}{{\widehat{V}}_{ideal}} = \frac{P\widehat{V}}{RT}\]</span></p>
</div>
<p>באמצעות הגדרה זו, אנו יכולים לכתוב מחדש את משוואת המצב בצורה המתוקנת הבאה:</p>
<p><span class="math display">\[P\widehat{V} = ZRT\quad\text{או}\quad PV = ZnRT\]</span></p>
<p>כאשר V הוא הנפח הכולל ו-n הוא מספר המולים. משוואה זו זהה בצורתה למשוואת הגז האידיאלי, כאשר כל "חוסר האידיאליות" מקופל בתוך הפרמטר היחיד Z.</p>
<p>כאשר <span class="math inline">\(Z = 1\)</span>, מתקבלת בדיוק משוואת הגז האידיאלי, והמשמעות היא שהגז מתנהג בקירוב אידיאלי בתנאי התהליך הנתונים. סטייה של <span class="math inline">\(Z\)</span> מערך זה מעידה על כך שהנפח המולרי של הגז שונה מן הנפח שהיה מתקבל אילו ההתנהגות הייתה אידיאלית לחלוטין. כאשר <span class="math inline">\(Z \neq 1\)</span>, Z מייצג השפעה מצטברת של מספר תופעות פיזיקליות הקשורות לכוחות משיכה ודחייה בין-מולקולריים ולנפח העצמי של המולקולות. עם זאת, באופן כללי נתון להגיד שכאשר מתקבל <span class="math inline">\(Z &lt; 1\)</span>, פירוש הדבר הוא שהנפח המולרי האמיתי של הגז קטן מן הנפח האידיאלי הצפוי. מצב זה מאפיין לרוב טמפרטורות בינוניות-נמוכות שבהן השפעת כוחות המשיכה בין המולקולות בולטת יותר, כך שהגז “דחוס” יותר מכפי שמנבא המודל האידיאלי. לעומת זאת, כאשר מתקבל <span class="math inline">\(Z &gt; 1\)</span> , הנפח המולרי גדול מן הערך האידיאלי, תופעה הקשורה להשפעת הנפח העצמי של המולקולות ולדחייה קצרי־טווח ביניהן, ונפוצה יותר בלחצים גבוהים.</p>
<p>אבל כיצד נמצא את ערך של Z? הערך של Z אינו קבוע; הוא משתנה עבור כל גז, ותלוי בטמפרטורה ובלחץ הספציפיים שבהם הוא נמצא. כיצד ניתן לקבוע את Z עבור גז נתון בתנאי לחץ וטמפרטורה נתונים? כדי לאפשר הכללה, נשתמש בתכונות קריטיות ובחוק המצבים התואמים, שמאפשרים להעריך <span class="math inline">\(Z\)</span>עבור גזים שונים באמצעות משתנים חסרי מימד. כדי להבין זאת, נחזור בקצרה לדיאגרמת הפאזות (P-T diagram) המוכרת ונחדד מספר הגדרות חשובות שישמשו אותנו בחישובים.</p>
<div class="callout callout-style-simple callout-note no-icon">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-body-container">
<p>מקדם הדחיסות</p>
<p>חקרו כיצד משתנים הלחץ והטמפרטורה משפיעים על מקדם הדחיסות (<span class="math inline">\(Z\)</span>) עבור גזים שונים, וזהו את האזורים בהם משוואת הגז האידיאלי אינה תקפה</p>
<iframe src="simulations/real-gas.html" width="100%" height="600px" style="border:none;">
</iframe>
</div>
</div>
</div>
<p>דיאגרמת פאזות מתארת אילו מצבי חומר יציבים עבור ערכי לחץ וטמפרטורה שונים. בדיאגרמה זו ניתן לראות שעקומת שיווי-המשקל בין נוזל לגז (עקומת הרתיחה) אינה נמשכת עד אינסוף. היא מסתיימת בנקודה ספציפית הנקראת הנקודה הקריטית.</p>
<div class="callout callout-note definition" title="הגדרה" data-collapse="false">
<p>טמפרטורה קריטית <span class="math inline">\(T_{c}\)</span> -הטמפ' הגבוהה ביותר שבה החומר יכול להתקיים במצב צבירה נוזלי, מעל לטמפ' זו האנרגיה הקינטית של המולקולות גבוהה מדי מכדי שכוחות המשיכה יחזיקו אותן יחד כנוזל, לא משנה כמה לחץ נפעיל עליהן.</p>
</div>
<div class="callout callout-note definition" title="הגדרה" data-collapse="false">
<p>לחץ קריטי <span class="math inline">\(P_{c}\)</span> - הלחץ הדרוש על מנת לנזל את הגז בדיוק בטמפ' הקריטית שלו</p>
</div>
<p>תכונה חשובה אחת היא ההבחנה בין גז לאדים. למרות שבשפת היום-יום אנו משתמשים במונחים "גז" ו"אדים" בערבוביה, בהנדסת תהליכים ישנה אבחנה ברורה ביניהם.</p>
<div class="callout callout-note definition" title="הגדרה" data-collapse="false">
<p>אדים - חומר במצב גזי הנמצא מתחת לטמפ' הקריטית שלו <span class="math inline">\(T &lt; T_{c}\)</span>, והאדים ניתנים לעיבוי על ידי הפעלת לחץ בלבד (דחיסה איזורתמית).</p>
</div>
<div class="callout callout-note definition" title="הגדרה" data-collapse="false">
<p>גז - חומר במצב גזים מעל הטמפ' הקריטית <span class="math inline">\(T &gt; T_{c}\)</span>, הגז אינו ניתן לעיבוי על ידי העלאת הלחץ בלבד.</p>
</div>
<p>בקרבת הנקודה הקריטית ההבדל בין נוזל לגז “מיטשטש”, ותכונות החומר משתנות באופן רגיש במיוחד לתנאים. למצב צבירה זה אנו קוראים זורם סופר קריטי</p>
<div class="callout callout-note definition" title="הגדרה" data-collapse="false">
<p><strong>זורם סופר-קריטי (Supercritical Fluid):</strong> מצב שבו החומר נמצא מעל הטמפרטורה הקריטית<br>
(<span class="math inline">\(T &gt; T_{c}\)</span>) ומעל הלחץ הקריטי (<span class="math inline">\(P &gt; P_{c}\)</span>). לחומר יש צפיפות גבוהה המזכירה נוזל, אך צמיגות נמוכה ויכולת דיפוזיה המזכירה גז. (תכונות אלו הופכות אותו לממס מצוין בתעשייה, למשל במיצוי קפאין מפולי קפה).</p>
</div>
<p>אולם חשיבותם של הערכים הקריטיים (<span class="math inline">\(\mathbf{T}_{\mathbf{c}}\mathbf{,}\mathbf{P}_{\mathbf{c}}\)</span>) חורגת מעבר להגדרת מצבי הצבירה. נקודות ציון פנימיות אלו מספקות לנו את המפתח להשוואה אמיתית בין חומרים שונים. האם יש קשר בין ההתנהגות של גזים שונים? במבט ראשון, נראה שהתשובה היא לא. אם נשרטט גרף של מקדם הדחיסות (Z) כתלות בלחץ עבור מגוון גזים בטמפרטורה אחידה יראה כאילו כל גז מתנהג אחרת לגמרי: גז אחד נדחס מאוד (Z יורד תלולות), אחר כמעט ולא משתנה, ושלישי בכלל מראה סטייה חיובית. נדמה שאין שום דרך לחזות התנהגות של גז אחד על סמך גז אחר. אך כשמסתכלים לעומק ניתן לראות שהמבנה הכללי של העקומות דומה עבור כל הגזים, הגרף מתחיל ב<span class="math inline">\(z = 1\)</span> בלחץ אפס. ככל שמעלים את הלחץ, ברוב המקרים הגרף יורד תחילה (השפעת כוחות משיכה) ואז, בלחצים גבוהים יותר, עולה בתלילות כלפי מעלה (השפעת כוחות דחייה).</p>
<p>הדמיון הזה במבנה מרמז לנו שהפיזיקה הבסיסית הפועלת על מולקולות חמצן היא אותה פיזיקה הפועלת על מולקולות מתאן. ההבדל ביניהן הוא לא ב"חוקים", אלא ב"סקאלה" - בעוצמת הכוחות הפנימיים האופיינית לכל חומר. הבעיה בהשוואה הקודמת הייתה שהשתמשנו ב"סרגל מדידה" אבסולוטי (למשל, אטמוספירות וקלווין) עבור חומרים שהסקאלה הפנימית שלהם שונה לחלוטין. טמפרטורה של <span class="math inline">\(300K\)</span> נחשבת "לוהטת" עבור חנקן (הנמצא הרבה מעל הטמפרטורה הקריטית שלו) אך "קפואה" עבור מים (הנמצאים עמוק מתחתיה). לא הוגן להשוות ביניהם באותם תנאים. כדי למצוא את החוקיות במקום לשאול "מה הלחץ?" נשאל "עד כמה הלחץ הזה גבוה ביחס ללחץ הקריטי של החומר הספציפי?"</p>
<div class="callout callout-note definition" title="הגדרה" data-collapse="false">
<p>חוק המצבים התואמים (Law of Corresponding States)- החוק קובע שאם מנרמלים את התנאים ומסתכלים על הלחץ והטמפרטורה באופן יחסי לנקודה הקריטית של כל חומר, ניתן "ליישר" את התנהגות הגזים לפי עקומה אחת אוניברסלית.</p>
</div>
<section id="משתנים-מופחתים-reduced-variables" class="level4" data-number="5.5.1.1">
<h4 data-number="5.5.1.1" class="anchored" data-anchor-id="משתנים-מופחתים-reduced-variables"><span class="header-section-number">5.5.1.1</span> משתנים מופחתים (Reduced Variables)</h4>
<p>כדי ליישם את חוק המצבים התואמים ולהשוות בין חומרים שונים, עלינו לתרגם את תנאי התהליך שלנו לערכים יחסיים, חסרי יחידות. ערכים אלו נקראים <strong>משתנים מופחתים</strong>:</p>
<p><span class="math display">\[T_{r} = \frac{T}{T_{c}}\quad,\quad P_{r} = \frac{P}{P_{c}}\]</span></p>
<p>משתנים אלו מבטאים עד כמה הטמפרטורה והלחץ רחוקים מן הערכים הקריטיים האופייניים לחומר הנדון. באופן זה, שני גזים שונים הנמצאים באותו <span class="math inline">\(T_{r}\)</span> ואותו <span class="math inline">\(P_{r}\)</span>נמצאים במצב פיזיקלי דומה מבחינת “המרחק היחסי” שלהם מן הנקודה הקריטית, גם אם הערכים המוחלטים של <span class="math inline">\(T\ \)</span>ו <span class="math inline">\(P\)</span>-שונים לחלוטין. באמצעות המשתנים המופחתים וגרפי הדחיסות הכלליים אנו יכולים להעריך את ערכו של מקדם הדחיסות Z עבור גזים ריאליים.</p>
<p>הגרפים הבאים מציגים את ההתנהגות הכללית של פקטור הדחיסות <span class="math inline">\(Z\)</span> כפונקציה של לחץ וטמפרטורה מוקטנים. לצורכי המחשה והבנה, הגרפים חושבו באמצעות משוואת מצב של גז אמיתי, המשחזרת את המאפיינים הפיזיקליים העיקריים של ההתנהגות הנמדדת.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images\IntroToCHemEng2/media/image80.png" style="width:6.35417in;height:4.51927in" class="figure-img"></p>
<figcaption>Figure 35 - הגרף מציג את פקטור הדחיסות <span class="math inline">\(Z\)</span> כפונקציה של הלחץ המוקטן <span class="math inline">\(P_{r}\)</span>עבור טמפרטורות מוקטנות שונות <span class="math inline">\(T_{r}\)</span>. כל עקומה מייצגת איזותרמה. בלחצים נמוכים מתקבל <span class="math inline">\(Z \approx 1\)</span>, המעיד על התנהגות קרובה לגז אידיאלי. עבור טמפרטורות נמוכות מופיעה סטייה משמעותית מגז אידיאלי, המתבטאת בשקע ב-<span class="math inline">\(Z\)</span> וקשורה לכוחות משיכה בין המולקולות. הקו השחור מתאר את גבול הרוויה (אזור דו־פאזי- שיווי משקל בין נוזל לגז).</figcaption>
</figure>
</div>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images\IntroToCHemEng2/media/image81.png" style="width:6.49306in;height:4.61806in" class="figure-img"></p>
<figcaption>Figure 36 - פקטור הדחיסות <span class="math inline">\(Z\)</span> <strong>כתלות בלחץ מוקטן</strong> <span class="math inline">\(P_{r}\)</span> <strong>עבור איזותרמות שונות, מחושב לפי משוואת המצב Redlich-Kwong.</strong></figcaption>
</figure>
</div>
<p>הגרפים המוצגים כאן מתארים את ההתנהגות הכללית של פקטור הדחיסות <span class="math inline">\(Z\)</span> כפונקציה של לחץ וטמפרטורה מוקטנים. גרפים קלאסיים מסוג זה מבוססים במקור על אוסף רחב של נתונים אמפיריים שנמדדו עבור גזים שונים, ואשר עובדו לגרפים מוכללים (Generalized Compressibility Charts). במסגרת ספר זה, לצורכי הדגמה, הבנה ויצירת גרפים רציפים ונשלטים, ההתנהגות מחושבת באמצעות משוואת מצב של גז אמיתי (Redlich-Kwong). השימוש במודל מאפשר לשחזר את המאפיינים הפיזיקליים העיקריים של הגרפים האמפיריים, כגון סטייה מגז אידיאלי, הופעת אזור דו־פאזי, והתנהגות חריגה בקרבת הנקודה הקריטית<strong>. להצגה מדוייקת יותר המבוססת ישירות על נתונים אמפיריים, ראו איור 5.4 אצל Felder et al.&nbsp;(2016).</strong></p>
</section>
<section id="שימוש-בגרף-הדחיסות-הכללי---הלכה-למעשה" class="level4" data-number="5.5.1.2">
<h4 data-number="5.5.1.2" class="anchored" data-anchor-id="שימוש-בגרף-הדחיסות-הכללי---הלכה-למעשה"><span class="header-section-number">5.5.1.2</span> שימוש בגרף הדחיסות הכללי - הלכה למעשה</h4>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
עצה
</div>
</div>
<div class="callout-body-container callout-body">
<p>נניח, לשם הדגמה, כי נתונים לנו הלחץ (P) והטמפרטורה (T) של גז מסוים, ואנו מעוניינים לחשב את הנפח המולרי שלו (<span class="math inline">\(\widehat{V}\)</span>).</p>
<p><strong>1. נמצא</strong> את הערכים הקריטיים של הגז הספציפי - הטמפרטורה הקריטית <span class="math inline">\(T_{c}\)</span>והלחץ הקריטי <span class="math inline">\(P_{c}\)</span> מתוך טבלאות תרמודינמיות או נספחים בספר הקורס.</p>
<p><strong>2. נחשב</strong> את הטמפרטורה והלחץ המופחתים:</p>
<p><span class="math display">\[T_{r} = \frac{T}{T_{c}},P_{r} = \frac{P}{P_{c}}\]</span></p>
<p><strong>3. בגרף הדחיסות הכללי</strong><br>
- נאתר את הערך של <span class="math inline">\(P_{r}\)</span> על ציר ה - <span class="math inline">\(x\)</span>.</p>
<ul>
<li><p>נעלה אנכית עד למפגש עם האיזותרמה המתאימה ל- <span class="math inline">\(T_{r}\)</span>.</p></li>
<li><p>אם הערך המדויק של <span class="math inline">\(T_{r}\)</span> אינו מופיע, נעשה אינטרפולציה ויזואלית בין העקומות.</p></li>
<li><p>נקרא את ערך מקדם הדחיסות <span class="math inline">\(Z\)</span> מציר ה־<span class="math inline">\(y\)</span>.</p></li>
</ul>
<p><strong>4. נציב את</strong> <span class="math inline">\(Z\)</span> במשוואת המצב המתוקנת ונחשב את הנפח המולרי:</p>
<p><span class="math display">\[\widehat{V} = \frac{ZRT}{P}\]</span></p>
</div>
</div>
<div class="callout callout-example example" title="דוגמה" data-collapse="false">
<p>חישוב נפח גז חנקן בלחץ גבוה</p>
<p>נתונים שני מיכלים המכילים גז חנקן (<span class="math inline">\(N_{2}\)</span>) בטמפרטורה של <span class="math inline">\(200\,\text{K}\)</span> הראשון בלחץ של <span class="math inline">\(1\,\text{atm}\)</span> והשני בלחץ של <span class="math inline">\(100atm\)</span>. חשבו את הנפח המולרי של הגז בשני המיכלים בשתי דרכים:<br>
א. בהנחת גז אידיאלי.<br>
ב. באמצעות גרף הדחיסות הכללי (גז ריאלי).</p>
<p>פתרון</p>
<p>חלק א’: הנחת גז אידיאלי (<span class="math inline">\(\mathbf{Z} = \mathbf{1}\)</span>)</p>
<p>עבור המיכל הראשון</p>
<p><span class="math display">\[{\widehat{V}}_{ideal} = \frac{RT}{P} = \frac{0.08206\ \frac{L\ atm}{mol\ K}\ 200K}{1atm} = 16\frac{L}{mol}\]</span></p>
<p><span class="math display">\[{\widehat{V}}_{ideal} = \frac{RT}{P} = \frac{0.08206\ \frac{L\ atm}{mol\ K}\ 200K}{100atm} = 0.16\frac{L}{mol}\]</span></p>
<p>חלק ב’: שימוש בגרף הדחיסות</p>
<p>נתונים קריטיים לחנקן (מתוך טבלת נתונים) - <span class="math inline">\(T_{c} = 126.2K,\ P_{c} = 33.5atm\)</span></p>
<p>חישוב טמפקטורה מופחתת (עבור שני המיכלים) <span class="math inline">\(T_{r} = \frac{200K}{126.2K} \approx 1.58\)</span></p>
<p>עבור המיכל הראשון</p>
<p>נחשב לחץ מופחת</p>
<p><span class="math display">\[\ \ \ \ P_{r} = \frac{1atm}{33.5atm} \approx 0.03\]</span></p>
<p>ובגרף הדחיסות הכללי עבור <span class="math inline">\(P_{r} \ll 1\)</span> מתקבל <span class="math inline">\(Z = 1\)</span></p>
<p><span class="math display">\[{\widehat{V}}_{ideal} = Z\frac{RT}{P} = 1*\frac{0.08206\ \frac{L\ atm}{mol\ K}\ 200K}{1atm} = 0.16\frac{L}{mol}\]</span></p>
<p>וניתן לראות שבלחצים נמוכים הגז מתנהג כגז אידיאלי.</p>
<p>עבור המיכל השני</p>
<p><span class="math display">\[P_{r} = \frac{100}{33.5} \approx 2.98\]</span></p>
<p>ובגרף הדחיסות ניתן לראות שעבור <span class="math inline">\(P_{r} \approx 3,\ T_{r} \approx 1.6\)</span> מתקבל בקירוב <span class="math inline">\(Z \approx 0.86\)</span></p>
<p><span class="math display">\[{\widehat{V}}_{real} = Z\frac{RT}{P} = 0.86 \cdot \frac{0.08206\frac{L\ atm}{mol\ K} \cdot 200K}{100atm} = 0.14\]</span></p>
<table class="caption-top table">
<colgroup>
<col style="width: 7%">
<col style="width: 12%">
<col style="width: 39%">
<col style="width: 39%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;"><strong>מיכל</strong></th>
<th style="text-align: left;"><strong>לחץ (atm)</strong></th>
<th style="text-align: left;"><span class="math display">\[{\widehat{V}}_{ideal}\ \left( \frac{L}{mol} \right)\]</span></th>
<th style="text-align: left;"><span class="math display">\[{\widehat{V}}_{real}\ \left( \frac{L}{mol} \right)\]</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">1</td>
<td style="text-align: left;">1</td>
<td style="text-align: left;">16.41</td>
<td style="text-align: left;">16.41</td>
</tr>
<tr class="even">
<td style="text-align: left;">2</td>
<td style="text-align: left;">100</td>
<td style="text-align: left;">0.164</td>
<td style="text-align: left;">0.141</td>
</tr>
</tbody>
</table>
<p>במיכל הראשון אין הבדל מעשי בין המודלים - הסטייה מאידיאליות זניחה.<br>
במיכל השני, לעומת זאת, הנפח המולרי האמיתי קטן בכ־14-16% מהערך האידיאלי, עקב השפעת כוחות משיכה בין־מולקולריים בלחץ גבוה.</p>
</div>
<p>ההליך שתואר עד כה מתאים במיוחד למצבים שבהם הנעלם הוא הנפח V. אולם לעיתים נתון לנו נפח המיכל וכמות החומר, ואנו נדרשים לחשב דווקא את הלחץ P. במקרה כזה נוצרת תלות מעגלית: כדי למצוא את Zמהגרף יש לדעת את הלחץ המופחת <span class="math inline">\(P_{r}\)</span>, אך <span class="math inline">\(P_{r}\)</span>עצמו תלוי בלחץ:</p>
<p><span class="math display">\[P_{r} = \frac{P}{P_{c}} = \frac{ZnRT/V}{P_{c}}\]</span> מצבים כאלה נפוצים מאוד בעבודה הנדסית, והפתרון המקובל להם הוא שימוש בתהליך איטרטיבי פשוט.</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
עצה
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>שיטת הפתרון (איטרציה)</strong></p>
<ul>
<li><p>מנחשים ערך התחלתי ל<span class="math inline">\(Z\)</span> (בדרך כלל Z=1 כלומר התחלה מגז אידיאלי).</p></li>
<li><p>מחשבים את הלחץ P לפי הניחוש.</p></li>
<li><p>מחשבים את <span class="math inline">\(P_{r}\)</span> המתאים.</p></li>
<li><p>ניגשים לגרף ומוצאים את ערך <span class="math inline">\(Z\)</span> עבור <span class="math inline">\(P_{r}\)</span> ו־<span class="math inline">\(T_{r}\)</span>.</p></li>
<li><p>אם ערך Z שנקרא מהגרף קרוב לערך שניחשנו - הפתרון הושג.</p></li>
<li><p>אם לא, משתמשים בערך Z החדש כניחוש לסיבוב הבא וחוזרים על התהליך עד להתכנסות.</p></li>
</ul>
</div>
</div>
<div class="callout callout-example example" title="דוגמה" data-collapse="false">
<p>מיכל קשיח מכיל גז חנקן (<span class="math inline">\(N_{2}\)</span>) בטמפרטורה <span class="math inline">\(T = 200\text{ }K\)</span>. הנפח המולרי של הגז במיכל נמדד כ:</p>
<p><span class="math display">\[\widehat{V} = 0.200\ L/mol\]</span> חשבו את הלחץ <span class="math inline">\(P\)</span>של הגז בשתי דרכים:<br>
א. בהנחת גז אידיאלי.<br>
ב. כגז ריאלי באמצעות גרף הדחיסות הכללי</p>
<p>** א. עבור גז אידיאלי (<span class="math inline">\(Z = 1\)</span>)</p>
<p><span class="math display">\[P_{ideal} = \frac{RT}{\widehat{V}} = \frac{0.08206\frac{L\ atm}{mol\ K} \cdot 200K}{0.200\ L/mol} = 82\text{ }atm\]</span> ב. כגז ריאלי</p>
<p>נתונים קריטיים לחנקן: <span class="math inline">\(T_{c} = 126.2\text{ , }P_{c} = 33.5\text{ }atm\)</span></p>
<p>שלב 1: מחשבים <span class="math inline">\(\mathbf{T}_{\mathbf{r}}\)</span> (קבוע לכל האיטרציות)</p>
<p><span class="math display">\[\mathbf{T}_{\mathbf{r}} = \frac{\mathbf{T}}{\mathbf{T}_{\mathbf{c}}} = \frac{\mathbf{200}}{\mathbf{126}.\mathbf{2}} \approx \mathbf{1}.\mathbf{6}\]</span></p>
<p>שלב 2: איטרציה על <span class="math inline">\(\mathbf{Z}\)</span></p>
<p>מנחשים <span class="math inline">\(\mathbf{Z}\)</span> <strong>←</strong> מחשבים <span class="math inline">\(\mathbf{P} = \frac{\mathbf{ZRT}}{\widehat{\mathbf{V}}}\)</span> ← מחשבים <span class="math inline">\(\mathbf{P}_{\mathbf{r}} = \frac{\mathbf{P}}{\mathbf{P}_{\mathbf{c}}}\)</span> ← קוראים <span class="math inline">\(\mathbf{Z}\)</span> מהגרף עבור <span class="math inline">\(\left( \mathbf{T}_{\mathbf{r}},\mathbf{P}_{\mathbf{r}} \right)\)</span> ← חוזרים על התהליך עד שהתוצאה מתייצבת</p>
<p>נגדיר קבוע נוח:</p>
<p><span class="math display">\[P_{ideal} = \ \frac{RT}{\widehat{V}} = \frac{0.08206\frac{L\ atm}{mol\ K} \cdot 200K}{0.200L/mol} = 82atm\]</span> ולכן:</p>
<p><span class="math display">\[P(atm) = Z \cdot P_{ideal}(atm)\]</span></p>
<p>טבלת איטרציות</p>
<table class="caption-top table">
<colgroup>
<col style="width: 5%">
<col style="width: 9%">
<col style="width: 28%">
<col style="width: 40%">
<col style="width: 14%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;"><strong>איטרציה</strong></th>
<th style="text-align: left;"><strong>ניחוש</strong> <span class="math inline">\(\mathbf{Z}\)</span></th>
<th style="text-align: left;"><span class="math display">\[\mathbf{P(atm) = Z \cdot}\mathbf{P}_{\mathbf{ideal}}\mathbf{(atm)}\]</span></th>
<th style="text-align: left;"><span class="math display">\[\mathbf{P}_{\mathbf{r}}\mathbf{=}\frac{\mathbf{P}\left( \mathbf{atm} \right)}{\mathbf{33.5atm}}\]</span></th>
<th style="text-align: left;"><span class="math inline">\(\mathbf{Z}\)</span> <strong>חדש מהגרף (בערך)</strong></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">0</td>
<td style="text-align: left;">1.00</td>
<td style="text-align: left;">82</td>
<td style="text-align: left;">2.45</td>
<td style="text-align: left;">0.88</td>
</tr>
<tr class="even">
<td style="text-align: left;">1</td>
<td style="text-align: left;">0.88</td>
<td style="text-align: left;">72.2</td>
<td style="text-align: left;">2.15</td>
<td style="text-align: left;">0.90</td>
</tr>
<tr class="odd">
<td style="text-align: left;">2</td>
<td style="text-align: left;">0.90</td>
<td style="text-align: left;">73.9</td>
<td style="text-align: left;">2.21</td>
<td style="text-align: left;">0.90</td>
</tr>
</tbody>
</table>
<p>וניתן לראות שהפתרון מתכנס ל-<span class="math inline">\(\mathbf{Z} \approx \mathbf{0}.\mathbf{90},\mathbf{P} \approx \mathbf{74}\text{ }\mathbf{atm}\)</span>**</p>
<p>ניתן לראות כי הנחת הגז האידיאלי הייתה מעריכה את הלחץ בגז בכ10% יותר.</p>
</div>
</section>
<section id="חישוב-תכונות-תערובת-גזים-באמצעות-פקטור-הדחיסות-kays-rule" class="level4" data-number="5.5.1.3">
<h4 data-number="5.5.1.3" class="anchored" data-anchor-id="חישוב-תכונות-תערובת-גזים-באמצעות-פקטור-הדחיסות-kays-rule"><span class="header-section-number">5.5.1.3</span> חישוב תכונות תערובת גזים באמצעות פקטור הדחיסות (Kay’s Rule)</h4>
<p>כיצד ניתן להעריך את מקדם הדחיסות <span class="math inline">\(Z\ \)</span>עבור תערובת גזים, כאשר לכל רכיב בתערובת ערכים קריטיים שונים? גישה נפוצה ופשוטה, המתאימה ליישומים הנדסיים רבים, היא כלל קיי (Kay’s Rule). לפי כלל זה, ניתן להתייחס אל תערובת הגזים כאילו הייתה “גז מדומה” יחיד, אשר תכונותיו הקריטיות מחושבות כממוצע משוקלל של התכונות הקריטיות של רכיביה. תכונות אלו נקראות תכונות פסאודו־קריטיות.</p>
<div class="callout callout-note definition" title="הגדרה" data-collapse="false">
<p>הטמפרטורה הפסאודו־קריטית של התערובת מוגדרת כ:</p>
<p><span class="math display">\[T_{c,\text{mix}} = \sum_{i}^{}y_{i}\text{ }T_{c,i}\]</span> והלחץ הפסאודו־קריטי מוגדר כ:</p>
<p><span class="math display">\[P_{c,\text{mix}} = \sum_{i}^{}y_{i}\text{ }P_{c,i}\]</span></p>
<p>כאשר <span class="math inline">\(y_{i}\)</span> הוא השבר המולי של רכיב <span class="math inline">\(i\)</span> בתערובת, ו-<span class="math inline">\(T_{c,i}\)</span> ו-<span class="math inline">\(P_{c,i}\)</span> הם הערכים הקריטיים של אותו רכיב טהור.</p>
</div>
<p>לאחר חישוב הערכים הפסאודו־קריטיים, ממשיכים בדיוק כפי שנעשה עבור גז טהור: מחשבים את המשתנים המופחתים של התערובת,</p>
<p><span class="math display">\[T_{r} = \frac{T}{T_{c,\text{mix}}},P_{r} = \frac{P}{P_{c,\text{mix}}}\]</span></p>
<p>קוראים את ערך מקדם הדחיסות <span class="math inline">\(Z\)</span> מתוך גרף הדחיסות הכללי עבור ערכים אלו ומציבים במשוואת המצב</p>
<blockquote class="blockquote">
<p><span class="math display">\[V_{total} = \frac{Zn_{total}RT}{P}\]</span></p>
</blockquote>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
עצה
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>מתי כלל קיי עובד?</strong></p>
<p>כלל קיי הוא קירוב לינארי פשוט. הוא מספק דיוק טוב (שגיאה של אחוזים בודדים) עבור תערובות של גזים בעלי מבנה כימי דומה (למשל תערובת של גזים אינרטיים או סדרה הומולוגית של פחמימנים). עבור תערובות של גזים שונים מאוד באופיים (למשל מולקולות קוטביות מאוד מעורבבות עם לא-קוטביות), הדיוק של הכלל יורד, אך בקורס מבוא זה הוא ישמש אותנו ככלי העיקרי לפתרון בעיות בתערובות.</p>
</div>
</div>
<div class="callout callout-important exercise" title="תרגיל" data-collapse="false">
<p>תערובת גזים מכילה <span class="math inline">\(80\%\)</span> חנקן (<span class="math inline">\(N_{2}\)</span>) ו- <span class="math inline">\(20\%\)</span> פחמן דו־חמצני (<span class="math inline">\(CO_{2}\)</span>) (שברים מולריים). התערובת נמצאת בטמפרטורה <span class="math inline">\(T = 300\,\)</span> ובלחץ <span class="math inline">\(P = 50\, atm\)</span>. חשבו את הנפח המולרי הריאלי של התערובת.</p>
<div class="live-exercise">
  <div class="le-row"><span class="le-prompt">T<sub>c,mix</sub> =</span>
    <input class="le-input" type="text" inputmode="decimal" data-answer="162" data-tol="1.5" placeholder="?" aria-label="טמפרטורה פסאודו-קריטית">
    <span class="le-unit">K</span></div>
  <div class="le-row"><span class="le-prompt">P<sub>c,mix</sub> =</span>
    <input class="le-input" type="text" inputmode="decimal" data-answer="41.6" data-tol="0.5" placeholder="?" aria-label="לחץ פסאודו-קריטי">
    <span class="le-unit">atm</span></div>
  <div class="le-row"><span class="le-prompt">V̂ (ריאלי) =</span>
    <input class="le-input" type="text" inputmode="decimal" data-answer="0.47" data-tol="0.04" placeholder="?" aria-label="נפח מולרי ריאלי">
    <span class="le-unit">L/mol</span></div>
  <div class="le-actions"><button class="le-check" type="button">בדיקה</button></div>
  <div class="le-feedback" role="status"></div>
  <div class="le-hint">V̂ תלוי בקריאת Z מהגרף (Z≈0.95) — ראו הפתרון המלא למטה.</div>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled" title="פתרון">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-16-contents" aria-controls="callout-16" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
פתרון
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-16" class="callout-16-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>נוציא נתונים קריטיים מהטבלה</p>
<p>חנקן - <span class="math inline">\(T_{c} = 126.2\text{ , }P_{c} = 33.5atm\)</span></p>
<p>פחמן דו חמצני <span class="math inline">\(T_{c} = 304.2K\text{ , }P_{c} = 73.8\ atm\)</span></p>
<p>השברים המולריים בתערובת:</p>
<p><span class="math display">\[y_{N_{2}} = 0.80,y_{CO_{2}} = 0.20\]</span></p>
<p>נחשב תכונות פסאודו־קריטיות (Kay’s Rule)</p>
<p>טמפרטורה פסאודו־קריטית <span class="math inline">\(T_{c,\text{mix}} = \sum_{i}^{}y_{i}T_{c,i} = 0.80 \cdot 126.2K + 0.20 \cdot 304.2K = 161K\)</span><em>* לחץ פסאודו־קריטי: <span class="math inline">\(P_{c,\text{mix}} = \sum_{i}^{}y_{i}P_{c,i} = 0.80 \cdot 33.5atm + 0.20 \cdot 73.8atm = 41.6atm\)</span></em>*</p>
<p>נחשב משתנים מופחתים</p>
<p><span class="math display">\[{T_{r} = \frac{T}{T_{c,\text{mix}}} = \frac{300K}{161.8K} \approx 1.85
}{P_{r} = \frac{P}{P_{c,\text{mix}}} = \frac{50atm}{41.56atm} \approx 1.20
}\]</span></p>
<p>ניגש לגרף הדחיסות הכללי ונאתר את <span class="math inline">\(P_{r} \approx 1.2\)</span>. עולים עד האיזותרמה המתאימה ל - <span class="math inline">\(T_{r} \approx 1.85\)</span><br>
קריאה מהגרף נותנת בקירוב:</p>
<p><span class="math display">\[Z \approx 0.95\]</span></p>
<p>ולכן הנפח המולרי של התערובת יהיה</p>
<p><span class="math display">\[\widehat{V} = \frac{ZRT}{P} = \frac{0.95 \cdot 0.08206\frac{L\ atm}{mol\ K} \cdot 300K}{50atm} = 0.47\ L/mol\]</span></p>
</div>
</div>
</div>
</section>
</section>
<section id="משוואות-מצב-של-גזים-ריאליים" class="level3" data-number="5.5.2">
<h3 data-number="5.5.2" class="anchored" data-anchor-id="משוואות-מצב-של-גזים-ריאליים"><span class="header-section-number">5.5.2</span> משוואות מצב של גזים ריאליים</h3>
<p>עד כה, הפתרון שלנו לסטייה מאידיאליות התבסס על גישה גרפית-אמפירית: השימוש במקדם הדחיסות (<span class="math inline">\(\mathbf{Z}\)</span>) ובחוק המצבים התואמים. גישה זו מצוינת להבנה אינטואיטיבית ולחישובים ידניים מהירים, שכן היא "מנרמלת" את התנהגות כל הגזים לתמונה ויזואלית אחת. אולם, לשיטה הגרפית ישנן מגבלות. קריאה מגרפים חשופה לשגיאות אנוש, היא אינה נוחה לשימוש בתוכנות מחשב ובסימולציות הנדסיות, והדיוק שלה מוגבל על ידי איכות הגרף והיכולת שלנו לבצע אינטרפולציה. יתרה מכך, כאשר אנו נדרשים לבצע חישובים מורכבים יותר (כגון חישובי שיווי-משקל פאזות או נגזרות תרמודינמיות), אנו זקוקים לביטוי מתמטי רציף ומדויק, ולא רק לערך נקודתי מתוך גרף. כאן נכנסות לתמונה משוואות המצב (Equations of State - EOS).</p>
<p>קיימות שתי גישות עיקריות לפיתוח משוואות מצב לגזים ריאליים. הגישה הוויראלית מתארת את הסטייה מהתנהגות אידיאלית באמצעות פיתוח סדרתי של מקדם הדחיסות בתחום תנאים נתון, ולכן היא מדויקת בעיקר בלחצים נמוכים ומתאימה לניתוח תיאורטי. הגישה הקובית, לעומת זאת, בונה משוואת מצב סגורה אחת הכוללת תיקונים פשוטים לדחייה ולמשיכה בין־מולקולרית, ומאפשרת תיאור רציף של התנהגות החומר בטווח רחב של תנאים, כולל מעבר בין גז לנוזל.</p>
<section id="המשוואה-הוויראלית-the-virial-equation" class="level4" data-number="5.5.2.1">
<h4 data-number="5.5.2.1" class="anchored" data-anchor-id="המשוואה-הוויראלית-the-virial-equation"><span class="header-section-number">5.5.2.1</span> המשוואה הוויראלית (The Virial Equation)</h4>
<p>אחת הגישות התיאורטיות החזקות ביותר לתיאור גזים ריאליים מגיעה מהמכניקה הסטטיסטית. במקום לנסות "לתקן" את המודל האידיאלי באופן שרירותי,</p>
<div class="callout callout-note definition" title="הגדרה" data-collapse="false">
<p>המשוואה הוויראלית מציגה את מקדם הדחיסות <span class="math inline">\(\mathbf{Z}\)</span> כטור חזקות אינסופי (טור טיילור) של הצפיפות המולרית (<span class="math inline">\(\mathbf{1}\textit{\textbf{/}}\widehat{\mathbf{V}}\)</span>)</p>
<p><span class="math display">\[Z = \frac{P\widehat{V}}{RT} = 1 + \frac{B(T)}{\widehat{V}} + \frac{C(T)}{\widehat{V^{2}}} + \frac{D(T)}{\widehat{V^{3}}} + ...\]</span></p>
<p>המקדמים <span class="math inline">\(\mathbf{B,\ C,\ D\ldots}\)</span> נקראים <strong>המקדמים הוויראליים</strong> (Virial Coefficients) . הם תלויים בטמפרטורה בלבד ועבור כל חומר הם שונים.</p>
</div>
<p>לייצוג המתמטי הזה יש משמעות פיזיקלית עמוקה:</p>
<ul>
<li><p>האיבר הראשון מייצג את הגז האידיאלי (ללא אינטראקציות).</p></li>
<li><p>האיבר השני, <span class="math inline">\(\mathbf{B}\left( \mathbf{T} \right)\textit{\textbf{/}}\widehat{\mathbf{V}}\)</span>, מייצג את האינטראקציות בין <strong>זוגות</strong> של מולקולות (התנגשויות בינאריות).</p></li>
<li><p>האיבר השלישי, <span class="math inline">\(\mathbf{C}\left( \mathbf{T} \right)\textit{\textbf{/}}\widehat{\mathbf{V}^{\mathbf{2}}}\)</span>, מייצג אינטראקציות בין <strong>שלשות</strong> של מולקולות, וכן הלאה.</p></li>
</ul>
<p>ככל שהצפיפות נמוכה יותר, תרומתם של האיברים הגבוהים בטור קטנה, והמשוואה מתכנסת במהירות.</p>
<p>בפועל, לרוב מסתפקים באיבר או בשני האיברים הראשונים של הפיתוח. ומחשבים לפי</p>
<p><span class="math display">\[Z \approx 1 + B(T)\text{ }P\]</span></p>
<p>קירוב זה מספק תיאור מדויק למדי בלחצים נמוכים עד בינוניים, והוא שימושי במיוחד כאשר הסטייה מהאידיאליות קטנה.</p>
<p>יתרונה המרכזי של המשוואה הוויראלית הוא הבסיס התיאורטי שלה: המקדמים הוויראליים ניתנים, עקרונית, לגזירה מתוך מכניקה סטטיסטית, ולכן יש להם משמעות פיזיקלית מוגדרת. עם זאת, חישוב או מדידה של מקדמים מסדר גבוה הוא מורכב, ולעיתים קרובות אינו מעשי. מסיבה זו, השימוש במשוואה הוויראלית מוגבל לרוב לתחום תנאים מצומצם ואינו מתאים לתיאור מעבר פאזה או להתנהגות נוזלית. לתיאור התנהגות החומר בטווח רחב יותר של תנאים, ובפרט כאשר נדרש תיאור של פאזה נוזלית ומעבר פאזה, נשתמש במשוואות מצב קוביות.</p>
</section>
<section id="משוואות-מצב-קוביות-cubic-equations-of-state" class="level4" data-number="5.5.2.2">
<h4 data-number="5.5.2.2" class="anchored" data-anchor-id="משוואות-מצב-קוביות-cubic-equations-of-state"><span class="header-section-number">5.5.2.2</span> משוואות מצב קוביות (Cubic Equations of State)</h4>
<p>דרך נוספת "לתקן" את משוואת הגז האידיאלי ולהתאים אותה למציאות הפיזיקלית היא על ידי התייחסות ישירה להנחות היסוד של מודל הגז האידיאלי ותיקון הקבועים הנובעים ממנו. במקרה זה אנו מקבלים משוואת מצב קובית הכוללת <strong>גורמי תיקון</strong> שמבטאים שני אפקטים פיזיקליים קריטיים:</p>
<ol type="1">
<li><p><strong>תיקון עבור כוחות דחייה (נפח עצמי) :</strong>המולקולות תופסות נפח ממשי במרחב ודוחות זו את זו כשהן קרובות מאוד. משוואות המצב הקוביות מתקנות זאת על ידי הפחתת "הנפח העצמי" של המולקולות מהנפח הכולל של הכלי.</p></li>
<li><p><strong>תיקון עבור כוחות משיכה :</strong>מולקולות מושכות זו את זו ממרחק, מה שמקטין את הלחץ שהן מפעילות על הדפנות. המשוואות כוללות איבר המפחית את הלחץ המחושב בהתאם לצפיפות הגז ועוצמת המשיכה.</p></li>
</ol>
<p>השם "משוואות קוביות" נובע מכך שהתוצאה המתמטית של שילוב תיקונים אלו היא משוואה, שכאשר מסדרים אותה אלגברית, מתקבל פולינום ממעלה שלישית בנפח המולרי (<span class="math inline">\(\widehat{\mathbf{V}}\)</span>).מבנה מתמטי זה הוא שמאפשר למשוואה אחת לתאר באופן רציף גם גז, גם נוזל וגם את נקודת הרתיחה ביניהם.</p>
<p><u>משוואת ואן-דר-ואלס</u></p>
<p>המשוואה הראשונה שהצליחה ליישם עקרונות אלו הוצעה בשנת 1873 על ידי הפיזיקאי ההולנדי יוהנס דידריק ואן-דר-ואלס (עליה זכה בפרס נובל לפיזיקה). ואן-דר-ואלס הציע שני קבועים ייחודיים לכל חומר: b המתקן את הנפח המולרי ו- a המתקן את הלחץ.</p>
<div class="callout callout-note definition" title="הגדרה" data-collapse="false">
<p>משוואת ואן דר ואלס לגזים אידיאליים <span class="math display">\[P = \frac{RT}{\widehat{V} - b} - \frac{a}{\widehat{V^{2}}}\]</span></p>
<p>התיקון הראשון (a) מתייחס לכוחות המשיכה בין המולקולות, אשר מפחיתים את הלחץ האפקטיבי שהגז מפעיל על דפנות הכלי. הפחתה זו נובעת מכך שמולקולות נמשכות זו אל זו ולא רק נעות באופן חופשי. הפרמטר <span class="math inline">\(a\)</span> מייצג את התרומה המצטברת של כוחות המשיכה הבין־מולקולריים, ומתאר את גודל התיקון ללחץ במשוואת המצב.</p>
<p>התיקון השני מתייחס לנפח אותו המולקולות תופסות. לא כל הנפח של הכלי זמין לתנועת מרכזי המסה של המולקולות. הנפח שאינו נגיש למולקולה אחת עקב נוכחותן של מולקולות אחרות נקרא <em>הנפח האסור</em>. הפרמטר <span class="math inline">\(b\)</span> מייצג, בקירוב, את סך הנפח האסור למול אחד של מולקולות.</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
עצה
</div>
</div>
<div class="callout-body-container callout-body">
<p>הנפח האסור <strong>אינו</strong> הנפח הפיזי של המולקולות עצמן. זהו נפח אפקטיבי גדול יותר, הנובע מהעובדה ששתי מולקולות אינן יכולות להתקרב זו לזו מעבר למרחק מינימלי. לכן <span class="math inline">\(b\)</span>גדול בערך פי כמה מהנפח הגאומטרי של המולקולות</p>
</div>
</div>
</div>
<p>אחד המאפיינים החשובים של משוואת ואן־דר־ואלס הוא שניתן לקשור את הפרמטרים a ו-b לערכים הקריטיים של החומר. באמצעות תנאי הנקודה הקריטית מתקבלים:</p>
<p><span class="math display">\[a = \frac{27R^{2}T_{c}^{2}}{64P_{c}},b = \frac{RT_{c}}{8P_{c}}\]</span></p>
<p>קשר זה מאפשר להשתמש במשוואת ואן־דר־ואלס גם כאשר ידועים רק הערכים הקריטיים של החומר.</p>
<p><u>משוואת רדליך-קוונוג (Redlich-Kwong EOS)</u></p>
<p>למרות האלגנטיות התיאורטית של משוואת ואן-דר-ואלס, השימוש המעשי בה הוגבל בשל חוסר דיוק כמותי. היא הצליחה להסביר "למה" גזים סוטים מאידיאליות, אך לא הצליחה לחזות "בכמה" בדיוק מספק לתכנון הנדסי מודרני. פריצת הדרך המעשית הגיעה בשנת 1949, כאשר אוטו רדליך וג'וזף קוונוג הציעו שיפור למודל. הם זיהו כי כוחות המשיכה בין המולקולות אינם קבועים, אלא מושפעים מהטמפרטורה של הגז. ככל שהטמפרטורה עולה, האנרגיה הקינטית של המולקולות גוברת, והאפקטיביות של כוחות המשיכה הבין-מולקולריים יורדת.</p>
<div class="callout callout-note definition" title="הגדרה" data-collapse="false">
<p>משוואת רדליך-קוונוג כדי לבטא זאת, הם שינו את איבר המשיכה במשוואה (האיבר השני) והוסיפו לו תלות בטמפרטורה (<span class="math inline">\(\mathbf{T}^{\mathbf{- 0.5}}\)</span>):</p>
<p><span class="math display">\[P = \frac{RT}{\widehat{V} - b} - \frac{a}{\sqrt{T}\widehat{V}\left( \widehat{V} + b \right)}\]</span></p>
</div>
<p>זוהי המשוואה ששימשה אותנו ליצירת גרפי ה Z בחלק הקודם. ההבדל המשמעותי ביחס למשוואת ואן-דר-ואלס הוא שאיבר המשיכה מכיל כעת את השורש של הטמפרטורה במכנה, והמכנה עצמו הפך למורכב יותר (<span class="math inline">\(\widehat{\mathbf{V}}\left( \widehat{\mathbf{V}}\mathbf{+ b} \right)\)</span> במקום <span class="math inline">\(\widehat{\mathbf{V}^{\mathbf{2}}}\)</span>. גם כאן, הפרמטרים a ו-b מחושבים מתוך הערכים הקריטיים של החומר, אך המקדמים המספריים שונים מאלו של ואן-דר-ואלס:</p>
<p><span class="math display">\[a = 0.42748\frac{R^{2}T_{c}^{2.5}}{P_{c}}\]</span></p>
<p><span class="math display">\[b = 0.08664\frac{RT_{c}}{P_{c}}\]</span></p>
<p>משוואת רדליך-קוונוג נחשבת לאחת ההצלחות הגדולות בתרמודינמיקה הנדסית. היא מספקת דיוק מצוין עבור גזים רבים בלחצים גבוהים (מעל ללחץ הקריטי) ובטמפרטורות שמעל לטמפרטורה הקריטית.</p>
<p>משוואות קוביות מתקדמות - (SRK, PR)</p>
<p>בהמשך למשוואת רדליך-קוונג פותחו משוואות מצב קוביות משופרות, אשר נועדו לשפר את הדיוק בתיאור תכונות של גזים ונוזלים בטווח רחב עוד יותר של תנאים. בין המשוואות הנפוצות ביותר ניתן למנות את משוואת Soave-Redlich-Kwong (SRK) ואת משוואת Peng-Robinson (PR).</p>
<p>שיפורים אלו מתמקדים בעיקר בתיאור מדויק יותר של איבר המשיכה, תוך התאמתו לסוג החומר ולטמפרטורה, ובשחזור טוב יותר של תכונות רוויה ולחץ אדים. מסיבה זו, משוואות SRK ו־PR משמשות כיום כסטנדרט בתעשיית הנפט והגז ומשולבות ברוב סימולטורי התהליכים התעשייתיים, כגון Aspen ו- HYSYS.</p>
<div class="callout callout-style-simple callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
אינטראקציה: השוואת מודלים (VdW, RK, Ideal)
</div>
</div>
<div class="callout-body-container callout-body">
<p>בסימולציה זו ניתן לראות את ההשוואה בין משוואת ואן דר ואלס, רדליך-קוונוג (RK) ומודל הגז האידיאלי.</p>
<iframe src="simulations/real-comparison.html" width="100%" height="600px" style="border:none;">
</iframe>
</div>
</div>
<p>משוואות מצב קוביות מובילות, לאחר סידור אלגברי, לפולינום ממעלה שלישית בנפח המולרי. כתוצאה מכך, עבור תנאים מסוימים עשויים להתקבל מספר פתרונות מתמטיים לנפח. מבין פתרונות אלו, רק הפתרונות המתאימים לפאזות יציבות (גז או נוזל) הם בעלי משמעות פיזיקלית, בעוד שהפתרון האמצעי חסר משמעות הנדסית.</p>
<div class="callout callout-example example" title="דוגמה" data-collapse="false">
<p>מיכל גלילי בנפח 0.150m<sup>3</sup> המכיל 22.7kg פרופן (C<sub>3</sub>H<sub>8</sub>) עומד בחצר המפעל. מד לחץ מראה כי הלחץ במיכל הוא 4790kPa gauge.<br>
מה הטמפ' במיכל על פי מקדם הדחיסות?<br>
מה היא הטמפ' במיכל בהנחה כי פרופן מתנהג כגז V.D.W?</p>
<p><strong>פתרון:</strong> נתוני המערכת: פרופן (<span class="math inline">\(C_{3}H_{8}\)</span>), מסה <span class="math inline">\(m = 22.7kg = 22,700g\)</span></p>
<p>נפח המיכל <span class="math inline">\(V = 0.150m^{3} = 150L\)</span> , לחץ <span class="math inline">\(P_{gauge} = 4790\ kPa\)</span></p>
<p>נוציא נתונים מהטבלה <span class="math inline">\(Mw = 44.09\frac{g}{mol}\)</span>, <span class="math inline">\(T_{c} = 369.9K,\ P_{c} = 42atm\)</span></p>
<p>לפני שנציב במשוואה, עלינו לוודא שכל היחידות תואמות.</p>
<p>נעבוד עם יחידות של <strong>אטמוספירות</strong> <strong>(atm)</strong>, <strong>ליטרים (L)</strong> ו-<strong>מולים (mol)</strong>, ולכן נשתמש בקבוע הגזים:</p>
<p><span class="math display">\[R = 0.08206\frac{L \cdot atm}{mol \cdot K}\]</span></p>
<p>נחשב מולים</p>
<p><span class="math display">\[n = \frac{m}{M_{w}} = \frac{22,700\, g}{44.09\, g\text{/}mol} = 514.86\, mol\]</span></p>
<p>נחשב נפח מולרי</p>
<p><span class="math display">\[\widehat{V} = \frac{V}{n} = \frac{150\, L}{514.86\, mol} = 0.2913\,\frac{L}{mol}\]</span></p>
<p>נחשב לחץ אבסולוטי.</p>
<p><span class="math display">\[P_{gauge} = 4790\, kPa*\frac{1atm}{101.325kPa} = 47.2736\, atm = 42.27\]</span></p>
<p>נניח כי הלחץ הוא אטמוספירי ולכן</p>
<p><span class="math display">\[P_{abs} = 47.27\, atm + 1\, atm = 48.27\, atm\]</span></p>
<p>נחשב את קבוע ון דר ואלס באמצעות הנתונים הקריטיים</p>
<p><span class="math display">\[a = \frac{27R^{2}T_{c}^{2}}{64P_{c}} = \frac{27 \cdot \left( 0.08206\frac{L \cdot atm}{mol \cdot K}\  \right)^{2} \cdot (369.9K)^{2}}{64 \cdot 42.0atm}\]</span></p>
<p><span class="math display">\[a = 9.256\,\frac{L^{2} \cdot atm}{mol^{2}}\]</span></p>
<p><span class="math display">\[b = \frac{RT_{c}}{8P_{c}} = \frac{0.08206\frac{L \cdot atm}{mol \cdot K} \cdot 369.9K}{8 \cdot 42.0atm} = 0.0903\ \frac{L}{mol}\]</span></p>
<p>נזכר במשוואת ון דר ואלס</p>
<p><span class="math display">\[P = \frac{RT}{\widehat{V} - b} - \frac{a}{{\widehat{V}}^{2}}\]</span></p>
<p><span class="math display">\[P + \frac{a}{\overline{{\widehat{V}}^{2}}} = \frac{RT}{\widehat{V} - b}\]</span></p>
<p><span class="math display">\[T = \frac{\left( \widehat{V} - b \right) \cdot \left( P + \frac{a}{\overline{{\widehat{V}}^{2}}} \right)}{R}\]</span></p>
<p>ונציב</p>
<p><span class="math display">\[P + \frac{a}{\overline{{\widehat{V}}^{2}}} = 48.27atm + \frac{9.256\frac{L^{2} \cdot atm}{mol^{2}}}{(0.2913\ L/mol)^{2}} = 48.27atm + 109.1atm = 157.37\, atm\]</span></p>
<p><span class="math display">\[\widehat{V} - b = 0.2913\,\frac{L}{mol} - 0.0903\,\frac{L}{mol} = 0.201\,\frac{L}{mol}\]</span></p>
<p><span class="math display">\[\boxed{T = \frac{0.201\frac{L}{mol} \cdot 157.37atm}{0.08206\frac{L \cdot atm}{mol \cdot K}} = 385.5K}\]</span></p>
<p>כדי לחשב על פי מקדם הדחיסות נמצא את הערכים המופחתים</p>
<p><span class="math display">\[T_{r} = \frac{T}{T_{c}} = \frac{T}{369.9K}\ \ \ \ ;\ \ \ \ P_{r} = \frac{P}{P_{c}} = \,\frac{48.27atm}{42atm} = 1.15\]</span></p>
<p>אם גרף הדחיסות שלנו מכיל נפחים מולרים נזכר ש</p>
<p><span class="math display">\[\widehat{V} = 0.2913\,\frac{L}{mol}\]</span></p>
<p>נחשב נפח מולרי מופחת</p>
<p><span class="math display">\[V_{r}' = \frac{0.2913\frac{L}{mol} \cdot 42.0atm}{0.08206\frac{L \cdot atm}{mol \cdot K} \cdot 369.9K} = \mathbf{0}.\mathbf{403}\]</span></p>
<p>ונוציא מהגרף את <span class="math inline">\(T_{r}\)</span> ואת <em>Z</em></p>
<p><span class="math display">\[Z = 0.45\ \ \ \ \ T_{r} = 1\  = &gt; T = T_{c} = 370K\]</span></p>
<p>אם אין את הנפח, חייבים לעבוד איטרטיבית<br>
איטרציה ראשונה</p>
<table class="caption-top table">
<colgroup>
<col style="width: 7%">
<col style="width: 9%">
<col style="width: 16%">
<col style="width: 53%">
<col style="width: 12%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">ניחוש <em>Z</em></th>
<th style="text-align: left;">מציאת <span class="math inline">\(T_{r}\)</span></th>
<th style="text-align: left;">חישוב <em>T</em></th>
<th style="text-align: left;">הצבה במשוואת הדחיסות</th>
<th style="text-align: left;"><em>Z</em> הנובע מהמשוואה</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">1</td>
<td style="text-align: left;">2.5</td>
<td style="text-align: left;"><span class="math display">\[T = 2.5*370K = 925K\]</span></td>
<td style="text-align: left;"><span class="math display">\[\frac{48.27atm*0.2913\,\frac{L}{mol}}{0.08206\frac{L \cdot atm}{mol \cdot K}*925K}\]</span></td>
<td style="text-align: left;"><em>0.185</em></td>
</tr>
<tr class="even">
<td style="text-align: left;"><em>0.2</em></td>
<td style="text-align: left;">הערכה 0.95</td>
<td style="text-align: left;"><span class="math display">\[T = 0.95*370K = 351K\]</span></td>
<td style="text-align: left;"><span class="math display">\[\frac{48.27atm*0.2913\,\frac{L}{mol}}{0.08206\frac{L \cdot atm}{mol \cdot K}*351K}\]</span></td>
<td style="text-align: left;"><em>0.4882</em></td>
</tr>
<tr class="odd">
<td style="text-align: left;"><em>0.5</em></td>
<td style="text-align: left;"><em>1.01</em></td>
<td style="text-align: left;"><span class="math display">\[T = 1.01*370K = 373K\]</span></td>
<td style="text-align: left;"><span class="math display">\[\frac{48.27atm*0.2913\,\frac{L}{mol}}{0.08206\frac{L \cdot atm}{mol \cdot K}*373K}\]</span></td>
<td style="text-align: left;"><em>0.46</em></td>
</tr>
<tr class="even">
<td style="text-align: left;"><em>0.46</em></td>
<td style="text-align: left;"><em>1</em></td>
<td style="text-align: left;"><span class="math display">\[T = 370K\]</span></td>
<td style="text-align: left;"><span class="math display">\[\frac{48.27atm*0.2913\,\frac{L}{mol}}{0.08206\frac{L \cdot atm}{mol \cdot K}*370K}\]</span></td>
<td style="text-align: left;"><em>0.46</em></td>
</tr>
</tbody>
</table>
<p>ורואים שהערך מתכנס ולכן** <span class="math display">\[T = 370K\]</span></p>
<p>לשם השוואה אם היינו מחשבים עם משוואת הגזיםה אידיאלים</p>
<p>עכשיו הטמפרטורה:</p>
<p><span class="math display">\[T = \frac{0.2913\,\frac{L}{mol}*48.27\, atm}{\left( 0.08206\frac{L \cdot atm}{mol \cdot K} \right)} = 171K\]</span></p>
<p>וזה בדיוק ה”דגל האדום” ההנדסי: בטמפרטורה כזו פרופן ממש לא יהיה גז אידיאלי בלחץ כזה (וגם לא בהכרח “גז” בכלל), ולכן קיבלנו טמפרטורה לא פיזיקלית לתיאור מצב המיכל - מה שמסביר למה כשמכניסים <span class="math inline">\(Z\)</span>או VdW מקבלים טמפרטורות גבוהות בהרבה.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 18%">
<col style="width: 15%">
<col style="width: 16%">
<col style="width: 48%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">המודל (Model)</th>
<th style="text-align: left;">הטמפרטורה שחישבנו (K)</th>
<th style="text-align: left;">הטמפרטורה בצלזיוס (∘C)</th>
<th style="text-align: left;">הערות</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">גז אידיאלי</td>
<td style="text-align: left;">171.4K</td>
<td style="text-align: left;">−101.7∘C</td>
<td style="text-align: left;">קסטרופה הנדסית. סטייה של מעל 50%. (מוכיח שההנחה Z=1 שגויה לחלוטין כאן).</td>
</tr>
<tr class="even">
<td style="text-align: left;">ואן דר ואלס (VDW)</td>
<td style="text-align: left;">385.5K</td>
<td style="text-align: left;">112.3∘C</td>
<td style="text-align: left;">קירוב טוב. התיקון לנפח ולמשיכה עשה את רוב העבודה, אך יש סטייה קלה למעלה.</td>
</tr>
<tr class="odd">
<td style="text-align: left;">רדליך-קוונג (RK)</td>
<td style="text-align: left;">383.5K</td>
<td style="text-align: left;">110.3∘C</td>
<td style="text-align: left;">שיפור של VDW, נחשבת למשוואה מדויקת יותר עבור גזים בלחץ גבוה.</td>
</tr>
<tr class="even">
<td style="text-align: left;">SRK (Soave-Redlich-Kwong)</td>
<td style="text-align: left;">382.1K</td>
<td style="text-align: left;">109.0∘C</td>
<td style="text-align: left;">הסטנדרט בתעשייה לפחמימנים. לוקחת בחשבון גם את הפקטור האקסנטרי (ω).</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Peng-Robinson (PR)</td>
<td style="text-align: left;">381.8K</td>
<td style="text-align: left;">108.6∘C</td>
<td style="text-align: left;">בדומה ל-SRK, נחשבת ל"חוד החנית" עבור נפט וגז.</td>
</tr>
</tbody>
</table>
<ul>
<li><p>האמת נמצאת ככל הנראה סביב <span class="math inline">\(382\, K\)</span></p></li>
<li><p>למה VDW זייף ב-3 מעלות? משוואת ואן דר ואלס מניחה שהמולקולות הן כדורים קשיחים מושלמים. פרופן הוא לא כדור, אלא שרשרת קטנה. המשוואות המודרניות (PR, SRK) מכילות פרמטר נוסף שנקרא הפקטור האקסנטרי (<span class="math inline">\(\omega\)</span>), שהוא בעצם מדד ל"כמה המולקולה לא כדורית". הפרופן, עם <span class="math inline">\(\omega = \ 0.152\)</span>, דורש את התיקון הזה כדי להגיע לדיוק מושלם.</p></li>
<li><p>סכנת הגז האידיאלי - אם מהנדס היה מתכנן את המיכל הזה לפי חוק הגזים האידיאליים, הוא היה חושב שהטמפרטורה היא מינוס 100 מעלות, בעוד שבפועל היא מעל 100 מעלות פלוס. פער של 200 מעלות שיכול לגרום לפיצוץ.</p></li>
</ul>
</div>
</section>
</section>
</section>
<section id="סיכום" class="level2" data-number="5.6">
<h2 data-number="5.6" class="anchored" data-anchor-id="סיכום"><span class="header-section-number">5.6</span> סיכום</h2>
<p><strong>מושגי יסוד ונוזלים</strong></p>
<ul>
<li><p><strong>מערכות חד-פאזיות:</strong> מערכות בהן החומר אחיד בתכונותיו (כגון צפיפות והרכב) בכל נקודה. בנוזלים ובמוצקים, הנפח משתנה מעט מאוד עם הלחץ והטמפרטורה, ולכן לרוב ניתן להניח שהצפיפות קבועה<sup>.</sup></p></li>
<li><p><strong>מקורות מידע לצפיפות:</strong> ניתן להשיג נתוני צפיפות מטבלאות ספרותיות, קורלציות אמפיריות (לחישוב בטמפרטורות שונות), או מדידה ניסיונית כאשר נדרש דיוק גבוה<sup>.</sup></p></li>
<li><p><strong>תערובות נוזלים:</strong> חישוב צפיפות תערובת מתבסס לרוב על <strong>הנחת חיבור נפחים</strong> (אדיטיביות), לפיה נפח התערובת הוא סכום נפחי הרכיבים. יש להבחין בין חישוב המבוסס על שברי מסה לבין זה המבוסס על שברי נפח<sup>.</sup></p></li>
</ul>
<p><strong>גזים אידיאליים</strong></p>
<ul>
<li><p><strong>משוואת הגז האידיאלי (</strong><span class="math inline">\(\mathbf{PV = nRT}\)</span><strong>):</strong> מודל המתאר גזים בהנחה שנפח המולקולות זניח ואין ביניהן אינטראקציות<sup>.</sup> המודל יעיל בלחצים נמוכים ובטמפרטורות גבוהות<sup>.</sup></p></li>
<li><p><strong>תנאים סטנדרטיים (STP/SATP):</strong> משמשים להשוואה נוחה. ב- STP (<span class="math inline">\(0^{\circ}C,1atm\)</span>) הנפח המולרי הוא <span class="math inline">\(22.4\ L\text{/}mol\)</span><sup>..</sup></p></li>
<li><p><strong>תערובות גזים אידיאליים:</strong> כל גז מתנהג באופן עצמאי. חוק דלתון - הלחץ הכולל הוא סכום הלחצים החלקיים, חוק אמגא - הנפח הכולל הוא סכום הנפחים החלקיים</p></li>
<li><p>בגז אידיאלי: שבר מולי = שבר נפחי = שבר לחץ<sup>.</sup></p></li>
</ul>
<p><strong>גזים ריאליים</strong></p>
<ul>
<li><p><strong>מקדם הדחיסות (</strong><span class="math inline">\(\mathbf{Z}\)</span><strong>):</strong> מתקן את משוואת הגז האידיאלי (<span class="math inline">\(PV = ZnRT\)</span>) כדי לתאר סטיות הנובעות מכוחות משיכה ודחייה בין המולקולות<sup>.</sup> כאשר <span class="math inline">\(Z = 1\)</span> הגז אידיאלי,<span class="math inline">\(Z &lt; 1\)</span> מעיד לרוב על דומיננטיות של כוחות משיכה, ו-<span class="math inline">\(Z &gt; 1\)</span> על כוחות דחייה ונפח עצמי.</p></li>
<li><p><strong>חוק המצבים התואמים:</strong> גזים שונים מתנהגים באופן דומה כאשר הם נמצאים באותו מרחק יחסי מהנקודה הקריטית שלהם. משתמשים במשתנים מופחתים (<span class="math inline">\(T_{r},P_{r}\)</span>) כדי למצוא את <span class="math inline">\(Z\)</span> מתוך גרף דחיסות כללי.</p></li>
<li><p><strong>כלל קיי (Kay's Rule):</strong> שיטה לחישוב <span class="math inline">\(Z\)</span> עבור <strong>תערובות</strong> גזים ריאליים, על ידי חישוב ערכים "פסאודו-קריטיים" (ממוצע משוקלל של <span class="math inline">\(T_{c}\)</span> ו-<span class="math inline">\(P_{c}\)</span> של הרכיבים)</p></li>
</ul>
<p><strong>משוואות מצב (EOS)</strong></p>
<ul>
<li><p><strong>המשוואה הוויראלית:</strong> טור חזקות תיאורטי המדויק בלחצים נמוכים-בינוניים.</p></li>
<li><p><strong>משוואות קוביות (Van der Waals, Redlich-Kwong):</strong> משוואות הנדסיות הכוללות פרמטרים לתיקון הנפח העצמי (<span class="math inline">\(b\)</span>) וכוחות המשיכה (<span class="math inline">\(a\)</span>). הן מאפשרות תיאור רציף של מעבר פאזה בין גז לנוזל. משוואת RK משפרת את הדיוק ע"י הוספת תלות בטמפרטורה לאיבר המשיכה.</p></li>
</ul>


</section>

</main> <!-- /main -->
<script>

/* הוספת כותרות אוטומטיות + צבע פסטלי לכל הסביבות (HTML),

   גם כשהכותרת כבר קיימת מ‑Quarto */

document.addEventListener('DOMContentLoaded', () => {

  function chapterNumber() {

    const h1 = document.querySelector('main h1[data-number]');

    if (h1 && h1.getAttribute('data-number')) return h1.getAttribute('data-number').split('.')[0];

    const sec = document.querySelector('.header-section-number');

    if (sec) return sec.textContent.trim().split('.')[0];

    return '1';

  }

  const chap = chapterNumber();



  const envs = {

    definition:  { label: 'הגדרה',   color: 'rgba(255, 99, 71, 0.4)',  numbered: true  },

    example:     { label: 'דוגמה',    color: 'rgba(138, 43, 226, 0.3)', numbered: true  },

    exercise:    { label: 'תרגיל',    color: 'rgba(30, 144, 255, 0.35)',numbered: true  }, // כחול פסטלי

    remark:      { label: 'הערה',     color: 'rgba(0, 0, 0, 0.15)',numbered: true  }, // ירוק פסטלי

    theorem:     { label: 'משפט',     color: 'rgba(255, 165, 0, 0.35)',    numbered: true  },

    lemma:       { label: 'למה',      color: 'rgba(255, 165, 0, 0.35)',    numbered: true  },

    proposition: { label: 'טענה',     color: 'rgba(255, 165, 0, 0.35)',    numbered: true  },

    corollary:   { label: 'מסקנה',    color: 'rgba(255, 165, 0, 0.35)',    numbered: true  },

    proof:       { label: 'הוכחה',    color: 'rgba60, 179, 113, 0.35)',    numbered: false }

  };



  const counters = Object.fromEntries(Object.keys(envs).map(k => [k, 0]));



  Object.keys(envs).forEach(env => {

    document.querySelectorAll(`div.${env}`).forEach(div => {

      const meta = envs[env];

      const hasTitle = div.querySelector(':scope > .theorem-title');



      // צור כותרת רק אם חסרה (לא נעצור אם קיימת!)

      if (!hasTitle) {

        const title = document.createElement('div');

        title.className = 'theorem-title';

        if (meta.numbered) {

          counters[env] += 1;

          title.textContent = `${meta.label} ${chap}.${counters[env]}`;

        } else {

          title.textContent = meta.label;

        }

        div.insertBefore(title, div.firstChild);

      }



      // תמיד הוסף envbox וצבע פסטלי

      div.classList.add('envbox');

      div.style.setProperty('--env-color', meta.color);



      // ניקוי "Remark./Proof." שנדבק לפסקה הראשונה

      const firstP = div.querySelector(':scope > p');

      if (firstP) {

        firstP.innerHTML = firstP.innerHTML.replace(/^\s*(Remark|Proof)\.?\s*/i, '');

      }

    });

  });

});

</script>

<script>

document.addEventListener('DOMContentLoaded', () => {

  // בחר את כל כותרות הפרקים הראשיים

  const chapters = document.querySelectorAll('main h1[data-number]');

  let counter = 0;

  chapters.forEach(h1 => {

    counter++;

    if (counter <= 3) {

      // שני פרקים ראשונים ברומי

      const roman = ['I','II'][counter-1];

      h1.setAttribute('data-number', roman);

      const numSpan = h1.querySelector('.header-section-number');

      if (numSpan) numSpan.textContent = roman;

    } else {

      // חזרה למספרים רגילים החל מ-1

      const normal = counter - 3;

      h1.setAttribute('data-number', normal);

      const numSpan = h1.querySelector('.header-section-number');

      if (numSpan) numSpan.textContent = normal;

    }

  });

});

</script>
<script>

document.addEventListener('DOMContentLoaded', () => {

  // מיפוי שם סביבה -> callout + כותרת

  const map = {

    definition: {callout:'callout-note',      title:'הגדרה'},

    example:    {callout:'callout-example',   title:'דוגמה'},

    exercise:   {callout:'callout-important', title:'תרגיל'},

    tip:        {callout:'callout-tip',       title:'טיפ'},

    summary:    {callout:'callout-important', title:'סיכום'},

    question:   {callout:'callout-note',      title:'שאלה'},

    answer:     {callout:'callout-tip',       title:'תשובה', collapse:true},

    remark:     {callout:'callout-note',      title:'הערה'},

    theorem:    {callout:'callout-note',      title:'משפט'},

    lemma:      {callout:'callout-note',      title:'למה'},

    proposition:{callout:'callout-note',      title:'טענה'},

    corollary:  {callout:'callout-note',      title:'מסקנה'},

    proof:      {callout:'callout-note',      title:'הוכחה', collapse:true},

    hint:       {callout:'callout-tip',       title:'רמז',   collapse:true},

    solution:   {callout:'callout-note',      title:'הצג פתרון', collapse:true},

  };



  // מאתרים גם לפי custom-style וגם לפי classes

  const candidates = [

    ...document.querySelectorAll('div[custom-style], section[custom-style]'),

    ...document.querySelectorAll(Object.keys(map).map(k => `div.${k}, section.${k}`).join(','))

  ];



  candidates.forEach(el => {

    const raw = (el.getAttribute('custom-style') || '')

                  .toLowerCase().replace(/\s+/g,'');

    const cls = [...el.classList].map(c=>c.toLowerCase());

    const key = Object.keys(map).find(k => k===raw || cls.includes(k));

    if (!key) return;



    const spec = map[key];



    // הפוך ל-callout: מוסיף מחלקות תואמות של Quarto

    el.classList.add('callout', spec.callout, key);



    // כותרת אם חסרה

    if (!el.getAttribute('title') && spec.title) {

      el.setAttribute('title', spec.title);

    }



    // collapse אם צריך

    if (spec.collapse && !el.getAttribute('collapse')) {

      el.setAttribute('collapse','true');

    }

  });

});

</script>

<div class="univ-footer">

  <div class="univ-footer__inner">

    <img src="assets/logo.png" alt="לוגו אוניברסיטת בן־גוריון" class="univ-footer__logo">

    <span class="univ-footer__text">אוניברסיטת בן־גוריון בנגב · © 2025</span>

  </div>

</div>
<script src="assets/tracking.js"></script>
<script src="assets/live-exercise.js"></script>

<script src="assets/report-error.js"></script>

<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "הועתק!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "הועתק!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
        const codeEl = trigger.previousElementSibling.cloneNode(true);
        for (const childEl of codeEl.children) {
          if (isCodeAnnotation(childEl)) {
            childEl.remove();
          }
        }
        return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./chapter4.html" class="pagination-link" aria-label="מאזני חומר">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">מאזני חומר</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./summary.html" class="pagination-link" aria-label="סיכום">
        <span class="nav-page-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">סיכום</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->




</body></html>